apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: database
  labels:
    app: mongodb
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
    tier: backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: database
spec:
  selector:
    matchLabels:
      app: mongodb 
      tier: backend
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb 
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/mongodb:4.1.7-v1
        volumeMounts:
        - mountPath: /data
          name: mongodb-vol
        ports:
        - containerPort: 27017
        resources: 
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 250m
            memory: 500Mi
  volumeClaimTemplates:
  - metadata:
      name: mongodb-vol
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 36Gi
      storageClassName: gp2