variable "region" {}
variable "dept" {}
variable "environment" {}
variable "config" {}
variable "org" {}
variable "stream_view_type" {}
variable "stream_enabled" {}
variable "billing_mode" {}
variable "hash_key" {}
variable "hash_key_type" {}
variable "write_capacity" {}
variable "table_prefix" {}
variable "tags" {}