---
# Creating K8s Service Account for Tiller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: default
---
# Bind "Cluter Admin" role to Tiller Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: default
