template_path: aws-global-accelerator.yaml
dependencies:
  - us-west-2/gateway-tier/nodes.yaml
#  - us-west-2/util-tier/nodes.yaml Temporary turned off for testing PoC

parameters:
  ###
  # Indicates whether the accelerator is enabled. The value is true or false. The default value is true.
  # If the value is set to true, the accelerator cannot be deleted. If set to false, accelerator can be deleted.
  GAenabled: 'true'
  # The name of the accelerator. The name must contain only alphanumeric characters or hyphens (-), and must not begin or end with a hyphen.
  GAname: 'prod-1-tcp'
  # Create tags for an accelerator.
  ENVprefix: 'prod-1'
  # An ID for the endpoint. If the endpoint is a Network Load Balancer or Application Load Balancer, this is the Amazon Resource Name (ARN) of the resource.
  # A resource must be valid and active when you add it as an endpoint. If the endpoint is an Elastic IP address, this is the Elastic IP address allocation ID.
  # For Amazon EC2 instances, this is the EC2 instance ID.
  TCPendpointId:  'arn:aws:elasticloadbalancing:us-west-2:407733091588:loadbalancer/net/a4f99f7a954a111ea81660a428a12de4/62ba545504099c94'
