# controlVersion: 2
# Docker image for pod
image:
  repository: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/appsflyer-consumer
  tag: 1.0.37

kind: Deployment

# Replica pod count
replicas: 3

# Labels
labels:
  metricsProm: true

# Update strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

# Anti/Affinity rules
affinity:
  nodeAffinity:
    key: prod-1-tier
    values: microservice
  podAntiAffinity:
    weight: 100
    key: app
    values: appsflyer-consumer
    topologyKey: kubernetes.io/hostname

# Container startup command
command:
  - "/bin/bash"
  - "-c"
  - "./start.sh $(JVM_ARGS) -Dlogging.level.com.withme.appsflyerconsumer=TRACE"

# Environment variables for pod
env:
  - name: JVM_ARGS
    value: "-Xmx1000m -Xms1000m"
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  - name: JAEGER_ENABLED
    value: "true"
  - name: JAEGER_UDP_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
    value: admin
  - name: SPRING_DATA_MONGODB_USERNAME
    valueFrom:
      secretKeyRef:
        name: appsflyer-consumer-mongo-auth
        key: username
  - name: SPRING_DATA_MONGODB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: appsflyer-consumer-mongo-auth
        key: password
  - name: SPRING_DATA_MONGODB_URI
    value: "mongodb+srv://$(SPRING_DATA_MONGODB_USERNAME):$(SPRING_DATA_MONGODB_PASSWORD)@appsflyer-consumer.nnq5y.mongodb.net/appsflyer-consumer?retryWrites=true&w=majority"

# Pod resources
resources: 
  requests:
    cpu: "250m"
    memory: "1250Mi"
  limits:
    # cpu: no limits
    memory: "1250Mi"

# livenessProbe configuration
livenessProbe:
  httpGet:
    path: /health/v1/lively
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 10

# livenessProbe configuration
readinessProbe:
  httpGet:
    path: /health/v1/ready
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 2

# Container ports
containerPorts:
  - containerPort: 8080

# k8s Service
service:
  # k8s Service type
  type: NodePort
  # k8s Service ports (If you adding new ports make sure that you set them in "containerPorts" too)
  ports:
    - port: 8080
      targetPort: 8080
      name: http-rest

##########################
##########################

# k8s Secret for microservice
secret:
  create: true
  name: "appsflyer-credentials"
  version: 1.0.0
  secretContents: {}
    # APPSFLYER_IOS_APP_ID: {}
    # APPSFLYER_PULL_API_TOKEN: {}


##########################
##########################

# K8s ServiceAccount for pod
serviceAccount:
  create: false
  # name: ""
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::407733091588:role/----