template_path: aws-elasticsearch.yaml
parameters:
  # Main network parameters for AWS ES Domain
  VpcId: !stack_output us-west-2/network/vpc.yaml::VpcId
  Subnets: !stack_output us-west-2/network/vpc.yaml::PrivSubnet01ID
  # Parameters for ElasticSearch AWS SecurityGroup
  ## Allow traffic to AWS ES from microservice-tier
  EC2SecurityGroupID: !stack_output us-west-2/microservice-tier/nodes.yaml::CustomSecurityGroup
  ESsecurityGroupName: 'perf-1-es-cleanspeak'
  ESsecurityGroupPort: '443'
  # Parameters for AWS ElasticSearch Domain
  DomainName: 'perf-1-es-cleanspeak'
  ESversion: '6.3'
  ZoneAwareness: 'false'
  AvailabilityZoneCount: '3'
  ## Parameters for ES Domain Master Instances
  DedicatedMaster: 'false'
  DedicatedMasterCount: '3'
  DedicatedMasterType: 'm3.medium.elasticsearch'
  ## Parameters for ES Domain Data Instances
  ESDataInstanceType: 't2.small.elasticsearch'
  ESDataInstanceCount: '1'
  ## Here we set default max value and that value can be tuned after load testing on the production environment.
  ESDataInstanceVolumeSize: '35'
