template_path: aws-rds.yaml
parameters:
  # Main network parameters
  VpcId: !stack_output us-west-2/network/vpc.yaml::VpcId
  Subnets:
    - !stack_output us-west-2/network/vpc.yaml::PrivSubnet01ID
    - !stack_output us-west-2/network/vpc.yaml::PrivSubnet02ID
    - !stack_output us-west-2/network/vpc.yaml::PrivSubnet03ID
  EC2SecurityGroupID: !stack_output us-west-2/microservice-tier/nodes.yaml::CustomSecurityGroup
  # RDS config
  EnvName: 'perf-1'
  RDSsecurityGroupName: 'perf-1-rds-cleanspeak'
  RDSsecurityGroupPort: '3306'
  RDSmultiAZ: 'false'
  ## The number of days for which automated backups are retained.
  BackupRetentionPeriod: '2'
  ## by UTC timezone from 01:00 to 03:00 AM by PST
  PreferredBackupWindow: '09:00-11:00'
  ## RDS instance EBS size in GB.
  RDSvolumeSize: '30'
  RDSstorageType: 'gp2'
  DBname: 'cleanspeak'
  ## RDS instance type.
  DBinstanceType: 'db.t3.medium'
  DBengine: 'MySQL'
  DBengineVer: '5.7.22'
  ## MySQL credentials config.
  RdsMasterUsername: 'administrator'
  ### Password will be fetched by automation (Jenkins pipeline or etc.) from Vault and passed trough env variable
  ### Password will be masked in CloudFormation outputs.
  MasterUserPassword: !environment_variable CLEANSPEAK_DATABASE_PASSWORD
  # Enable Cleanspeak DB Parameter group. If "true" Scepter will create Cleanspeak DB parameter group and apply it to RDS.
  DBenableParameterGroup: 'true'
  ## DB Parameter group configuration.
  DBParamGroupName: 'cleanspeak-services-perf-1'
  DBParamGroupFamily: 'mysql5.7'
