template_path: tier.yaml
parameters:
  ClusterName: int-2
  NodeGroupName: int-2-util
  NodeInstanceType: 't3.medium'
  NodeImageId: !resolver_yaml config/defaults.yml::EKS.NodeImageId
  KeyName: kubernetes-int-2-key-pair
  NodeAutoScalingGroupMinSize: '3'
  NodeAutoScalingGroupMaxSize: '6'
  NodeAutoScalingGroupDesiredCapacity: '5'
  NodeVolumeSize: '128'
  NodeLabelARG: '--node-labels=int-2-tier=util,istio=cp'
  KubeletReservedARG: '--kube-reserved cpu=250m,memory=1Gi,ephemeral-storage=1Gi'
  SystemReservedARG: '--system-reserved cpu=250m,memory=0.2Gi,ephemeral-storage=1Gi'
  EvictionHardARG: '--eviction-hard memory.available<500Mi,nodefs.available<10%'
  NodeSecurityGroup: sg-06492f12cc7958f69
  VpcId: !stack_output_external int-2-eks-vpc::VpcId
  Subnets: !stack_output_external int-2-eks-vpc::SubnetIds
