template_path: vpc.yaml
parameters:
  ClusterName: !resolver_yaml config/defaults.yml::EKS.ClusterName
  VpcId: 'vpc-0f4806d98b2185d4c'
  PublicSubnet01ID: 'subnet-06325f1744cf24b64'
  PublicSubnet02ID: 'subnet-031eebef444013653'
  NATGateway1ID: 'nat-05480c32b663bfff0'
  NATGateway2ID: 'nat-041a464c0a4ba46bc'
  PrivateSubnet01CIDR: 10.0.96.0/20
  PrivateSubnet02CIDR: 10.0.112.0/20