---
# Source: istio-init/templates/job-crd-10.yaml
apiVersion: batch/v1
kind: Job
metadata:
  namespace: istio-system
  name: istio-init-crd-10
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-init-service-account
      containers:
      - name: istio-init-crd-10
        image: "407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-cicd/istio/kubectl:1.1.11"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: crd-10
          mountPath: /etc/istio/crd-10
          readOnly: true
        command: ["kubectl",  "apply", "-f", "/etc/istio/crd-10/crd-10.yaml"]
      volumes:
      - name: crd-10
        configMap:
          name: istio-crd-10
      restartPolicy: OnFailure
