apiVersion: v1
kind: Service
metadata:
  name: account-manager-mongodb
  labels:
    component: mongodb
    database: account
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    component: mongodb
    tier: backend
    account: database
---
apiVersion: v1
kind: Service
metadata:
  name: account-manager
  labels:
    component: account-manager
    tier: account-management
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: http-rest
    - port: 8081
      targetPort: 8081
      name: grpc
    - port: 5005
      targetPort: 5005
      name: debug
  selector:
    component: account-manager
    tier: account-management
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-manager-deployment
  labels:
    component: account-manager
    tier: account-management
spec:
  selector:
    matchLabels:
      component: account-manager
  replicas: 1
  template:
    metadata:
      labels:
        component: account-manager
        tier: account-management
    spec:
      containers:
        - name: account-manager
          image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/account-manager:1.0.106
          command:
            - "/bin/bash"
            - "-c"
            - "./start.sh -Xms640m -Xmx640m -Dspring.profiles.active=local -Dlogging.level.com.withme.accountManager=DEBUG"
          livenessProbe:
            httpGet:
              path: /health/v1/lively
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health/v1/ready
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 2
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 5005
