apiVersion: v1
kind: Service
metadata:
  name: atlas-server-mongodb
  labels:
    component: mongodb
    database: atlas
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    component: mongodb
    tier: backend
    atlas: database
---
apiVersion: v1
kind: Service
metadata:
  name: atlas-server
  labels:
    component: atlas-server
    tier: atlas-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: http-rest
    - port: 8081
      targetPort: 8081
      name: grpc
  selector:
    component: atlas-server
    tier: atlas-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atlas-server-deployment
  labels:
    component: atlas-server
    tier: atlas-server
spec:
  selector:
    matchLabels:
      component: atlas-server
  replicas: 1
  template:
    metadata:
      labels:
        component: atlas-server
        tier: atlas-server
    spec:
      containers:
        - name: atlas-server
          image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/atlas-server:1.0.65
          command:
            - "/bin/bash"
            - "-c"
            - "./start.sh -Xms640m -Xmx640m -Dspring.profiles.active=local -Dlogging.level.com.withme.atlas=DEBUG"
          env:
            - name: DESTINATION_IMAGE_URL_DEFAULT
              value: "http://example.com/destination_fallback.png"
          livenessProbe:
            httpGet:
              path: /health/v1/lively
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health/v1/ready
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 2
          ports:
            - containerPort: 8080
            - containerPort: 8081
