image:
  name: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server-build/aws-cli:1.16.15v1
  aws:
    access-key: $AWS_EGO_ACCESS_KEY
    secret-key: $AWS_EGO_SECRET_KEY

pipelines:
  tags:
    logmgr-local-v*:
      - step:
          name: Build Base Docker Image
          script:
            - export SERVER=`echo "$BITBUCKET_TAG" | sed 's/\(.*\)-v\([0-9]*\.[0-9]*\.[0-9]*\)$/\1/'`
            - export VERSION=`echo "$BITBUCKET_TAG" | sed 's/\(.*\)-v\([0-9]*\.[0-9]*\.[0-9]*\)$/\2/'`
            - echo "Server = $SERVER  Version = $VERSION"
            - /aws/set-aws-credentials.sh --key-id $AWS_EGO_ACCESS_KEY --secret-access-key $AWS_EGO_SECRET_KEY
            - eval $(aws ecr get-login --region us-west-2 --no-include-email)
            - docker build -t "ego-server/$SERVER:$VERSION" -f logmgr/Dockerfile .
            - /aws/repo-create-if-absent.sh "ego-server/$SERVER"
            - docker tag "ego-server/$SERVER:$VERSION" "407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/$SERVER:$VERSION"
            - docker push "407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/$SERVER:$VERSION"
          services:
            - docker
