kind: ServiceAccount
apiVersion: v1
metadata:
  name: configuration-manager-service-account
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: configuration-manager
  labels:
    component: configuration-manager
    tier: configuration-manager
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: http-rest
    - port: 8081
      targetPort: 8081
      name: grpc
  selector:
    component: configuration-manager
    tier: configuration-manager
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: configuration-manager-deployment
  labels:
    component: configuration-manager
    tier: configuration-manager
spec:
  selector:
    matchLabels:
      component: configuration-manager
  replicas: 1
  template:
    metadata:
      labels:
        component: configuration-manager
        tier: configuration-manager
    spec:
      serviceAccountName: configuration-manager-service-account
      containers:
        - name: configuration-manager
          image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/configuration-manager:1.0.11
          command:
            - "/bin/bash"
            - "-c"
            - "./start.sh -Xms640m -Xmx640m -Dspring.profiles.active=local -Dlogging.level.com.withme.configurationmanager=DEBUG -Dlogging.level.com.withme.k8swatcher=DEBUG -Dlogging.level.com.withme.filebasedrepo=DEBUG"
          livenessProbe:
            httpGet:
              path: /health/v1/lively
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health/v1/ready
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 2
          ports:
            - containerPort: 8080
            - containerPort: 8081

