apiVersion: v1
kind: Service
metadata:
  name: content-manager-mongodb
  labels:
    component: mongodb
    database: content
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    component: mongodb
    tier: backend
    content: database
---
apiVersion: v1
kind: Service
metadata:
  name: content-manager
  labels:
    component: content-manager
    tier: content
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http-rest
  - port: 8081
    targetPort: 8081
    name: grpc
  selector:
    component: content-manager
    tier: content
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: content-manager-deployment
  labels:
    component: content-manager
    tier: content
spec:
  selector:
    matchLabels:
      component: content-manager
  replicas: 1
  template:
    metadata:
      labels:
        component: content-manager
        tier: content
    spec:
      containers:
      - name: content-manager
        image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/content-manager:1.0.54
        command:
          - "/bin/bash"
          - "-c"
          - "./start.sh -Xms640m -Xmx640m -Dspring.profiles.active=local"
        env:
          - name: EXTERNAL_URL_PREFIX
            value: https://service-gateway
          - name: CONTENT_CACHE_TTL
            value: "10m"
        livenessProbe:
          httpGet:
            path: /health/v1/lively
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health/v1/ready
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 2
        ports:
        - containerPort: 8080
        - containerPort: 8081