apiVersion: v1
kind: Service
metadata:
  name: example-server-mongodb
  labels:
    component: mongodb
    database: example
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    component: mongodb
    tier: backend
    example: database
---
apiVersion: v1
kind: Service
metadata:
  name: example-server
  labels:
    component: example-server
    tier: example
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http-rest
  - port: 8081
    targetPort: 8081
    name: grpc
  selector:
    component: example-server
    tier: example
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-server-deployment
  labels:
    component: example-server
    tier: example
spec:
  selector:
    matchLabels:
      component: example-server
  replicas: 1
  template:
    metadata:
      labels:
        component: example-server
        tier: example
    spec:
      containers:
      - name: example-server
        image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/example-server:1.0.13
        command:
        - "/bin/bash"
        - "-c"
        - "./start.sh -Xms640m -Xmx640m -Dspring.profiles.active=local"
        livenessProbe:
          httpGet:
            path: /health/v1/lively
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health/v1/ready
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
          failureThreshold: 2
        ports:
        - containerPort: 8080
        - containerPort: 8081
