apiVersion: v1
kind: Service
metadata:
  name: leaderboard-server-mongodb
  labels:
    component: mongodb
    database: leaderboard
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    component: mongodb
    tier: backend
    leaderboard: database
---
apiVersion: v1
kind: Service
metadata:
  name: leaderboard-server
  labels:
    component: leaderboard-server
    tier: leaderboard
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http-rest
  - port: 8081
    targetPort: 8081
    name: grpc
  selector:
    component: leaderboard-server
    tier: leaderboard
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: leaderboard-server-deployment
  labels:
    component: leaderboard-server
    tier: leaderboard
spec:
  selector:
    matchLabels:
      component: leaderboard-server
  replicas: 1
  template:
    metadata:
      labels:
        component: leaderboard-server
        tier: leaderboard
    spec:
      containers:
      - name: leaderboard-server
        image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/leaderboard-server:1.0.57
        env:
        - name: CS_USER_ACCOUNT_ID
          value: "test"
        - name: ALLOW_VALIDATION
          value: "true"
        command:
        - "/bin/bash"
        - "-c"
        - "./start.sh -Xms640m -Xmx640m -Dspring.profiles.active=local -Dlogging.level.com.withme.leaderboard=DEBUG -Dlogging.level.com.withme.configurationmanager=DEBUG"
        livenessProbe:
          httpGet:
            path: /health/v1/lively
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health/v1/ready
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
          failureThreshold: 2
        ports:
        - containerPort: 8080
        - containerPort: 8081
