apiVersion: v1
kind: Service
metadata:
  name: push-notification-server
  labels:
    component: push-notification-server
    tier: push-notification-server
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      name: grpc
    - port: 8080
      targetPort: 8080
      name: http-rest
  selector:
    component: push-notification-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: push-notification-server-deployment
  labels:
    component: push-notification-server
spec:
  selector:
    matchLabels:
      component: push-notification-server
  replicas: 1
  template:
    metadata:
      labels:
        component: push-notification-server
    spec:
      containers:
        - name: push-notification-server
          image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/push-notification-server:1.1.56
          command:
            - "/bin/bash"
            - "-c"
            - "./start.sh -Xms640m -Xmx640m -Dspring.profiles.active=local -Dpushnotification.firebase.send_url=http://mock-server:8080/fcm/send -Dlogging.level.com.withme.pushnotification=DEBUG"
          env:
            - name: AUTHENTICATION_SERVER_SERVICE_PORT_REST
              value: "8080"
          livenessProbe:
            httpGet:
              path: /health/v1/lively
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health/v1/ready
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 2
          ports:
            - containerPort: 8081
            - containerPort: 8080
