apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    component: redis
spec:
  selector:
    matchLabels:
      component: redis
  replicas: 1
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: redis
          image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/redis-server:5.0.9
          imagePullPolicy: IfNotPresent
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379
              name: main
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    component: redis
spec:
  type: NodePort
  selector:
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
