template_path: security-group-ingress.yaml

parameters:
  CustomSecurityGroupIngressGroupId: !stack_output us-west-2/eks/cluster.yaml::NodeSecurityGroup
  CustomSecurityGroupIngressType: "CidrIp"
  CustomSecurityGroupIngressFromPort: "53"
  CustomSecurityGroupIngressToPort: "53"
  CustomSecurityGroupIngressCIDR: "0.0.0.0/0"
  CustomSecurityGroupIngressProtocol: "UDP"
  CustomSecurityGroupIngressDescription: "Access to Core DNS"