---
AWSTemplateFormatVersion: 2010-09-09
Description: Custom Security group

Parameters:

  CustomSecurityGroupIngressType:
    Description: Type of a custom security group ingress record
    Type: String
    AllowedValues:
     - CidrIp
     - SourceGroup

  CustomSecurityGroupIngressFromPort:
    Description: Lowest port value of the ingress record. Might be the same as To Port in case of a single-port record
    Type: Number

  CustomSecurityGroupIngressToPort:
    Description: Higest port value of the ingress record. Might be the same as From Port in case of a single-port record
    Type: Number

  CustomSecurityGroupIngressGroupId:
    Description: Security group Id the ingress record needs to be attached to 
    Type: AWS::EC2::SecurityGroup::Id

  CustomSecurityGroupIngressSourceGroup:
    Description: ID of the source security group 
    Type: String
    Default: "Null"

  CustomSecurityGroupIngressCIDR:
    Description: CIDR of the source address
    Type: String
    Default: "Null"

  CustomSecurityGroupIngressProtocol:
    Description: IpProtocol of the ingress record
    Type: String

  CustomSecurityGroupIngressDescription:
    Description: Custom security group description
    Type: String


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Custom Security group configuration
        Parameters:
          - CustomSecurityGroupIngressType
          - CustomSecurityGroupIngressFromPort
          - CustomSecurityGroupIngressToPort
          - CustomSecurityGroupIngressGroupId
          - CustomSecurityGroupIngressSourceGroup
          - CustomSecurityGroupIngressCIDR
          - CustomSecurityGroupIngressProtocol
          - CustomSecurityGroupIngressDescription

Conditions:
  SourceGroupCondition:  !Equals [ !Ref CustomSecurityGroupIngressType, "SourceGroup" ]
  CidrIpCondition: !Equals [ !Ref CustomSecurityGroupIngressType, "CidrIp" ]

Resources:

  CustomSecurityGroupIngressSourceGroupType:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: SourceGroupCondition
    Properties:
      Description: !Ref CustomSecurityGroupIngressDescription
      GroupId: !Ref CustomSecurityGroupIngressGroupId
      SourceSecurityGroupId: !Ref CustomSecurityGroupIngressSourceGroup
      IpProtocol: !Ref CustomSecurityGroupIngressProtocol
      FromPort: !Ref CustomSecurityGroupIngressFromPort
      ToPort: !Ref CustomSecurityGroupIngressToPort

  CustomSecurityGroupIngressCidrIpType:
    Type: AWS::EC2::SecurityGroupIngress
    Condition: CidrIpCondition
    Properties:
      Description: !Ref CustomSecurityGroupIngressDescription
      GroupId: !Ref CustomSecurityGroupIngressGroupId
      CidrIp: !Ref CustomSecurityGroupIngressCIDR
      IpProtocol: !Ref CustomSecurityGroupIngressProtocol
      FromPort: !Ref CustomSecurityGroupIngressFromPort
      ToPort: !Ref CustomSecurityGroupIngressToPort

Outputs:

  CustomSecurityGroupIngressSourceGroupType:
    Condition: SourceGroupCondition
    Description: Custom Security group
    Value: !Ref CustomSecurityGroupIngressSourceGroupType

  CustomSecurityGroupIngressCidrIpType:
    Condition: CidrIpCondition
    Description: Custom Security group
    Value: !Ref CustomSecurityGroupIngressCidrIpType
