master:
  componentName: jenkins-master
  image: "407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-cicd/jenkins"
  imageTag: "2.235.1-lts-alpine"
# Default is false. If OverwriteConfig will be set as "true" existing config.xml will be rewritten with the parameters listed below.
# Reccomendation: Backup jenkins home directory before change to "true" if you will run that values.yaml against existing Jenkins deployment.
  overwriteConfig: false

# Enable SAML2.0 for new deployment jenkins from the scratch.
  securityRealm: |-
    <securityRealm class="org.jenkinsci.plugins.saml.SamlSecurityRealm" plugin="saml@1.1.2">
      <displayNameAttributeName>displayName</displayNameAttributeName>
      <groupsAttributeName>http://schemas.xmlsoap.org/claims/Group</groupsAttributeName>
      <maximumAuthenticationLifetime>86400</maximumAuthenticationLifetime>
      <emailAttributeName>mail</emailAttributeName>
      <usernameCaseConversion>none</usernameCaseConversion>
      <usernameAttributeName>http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name</usernameAttributeName>
      <binding>urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect</binding>
      <advancedConfiguration>
        <forceAuthn>false</forceAuthn>
        <spEntityId>Jenkins-users</spEntityId>
      </advancedConfiguration>
      <idpMetadataConfiguration>
        <xml>&lt;?xml version=&quot;1.0&quot;?&gt;
    &lt;md:EntityDescriptor xmlns:md=&quot;urn:oasis:names:tc:SAML:2.0:metadata&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; entityID=&quot;https://dag.corp.imvu.com/dag/saml2/idp/metadata.php&quot;&gt;
    &lt;md:IDPSSODescriptor protocolSupportEnumeration=&quot;urn:oasis:names:tc:SAML:2.0:protocol&quot;&gt;
      &lt;md:KeyDescriptor use=&quot;signing&quot;&gt;
        &lt;ds:KeyInfo xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
          &lt;ds:X509Data&gt;
            &lt;ds:X509Certificate&gt;MIIDYTCCAkmgAwIBAgIBADANBgkqhkiG9w0BAQsFADBLMQswCQYDVQQGEwJVUzELMAkGA1UECAwCTUkxEjAQBgNVBAcMCUFubiBBcmJvcjEbMBkGA1UECgwSRHVvIFNlY3VyaXR5LCBJbmMuMB4XDTE4MDMwNjIwNTI0MFoXDTI4MDMwMzIwNTI0MFowSzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1JMRIwEAYDVQQHDAlBbm4gQXJib3IxGzAZBgNVBAoMEkR1byBTZWN1cml0eSwgSW5jLjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALb+uWJmWMxAky+MgUDR9u5Ho/Wrx3V/zCAcoAN3dWnEwKYNJafLkjy+cyhrH6VkIpi1olcvrUXJ2wSXU8AZ93H4FCJz0gkiWyDOb5BIbd4tsTzJ6Y1ROGwv0jA2z4vinWd7LrptbQTQ2pOwffEpgG8A9BmLnxp7VxKWmvAPu//G+b2znwkvrRfq+gP1i8FOzbvbj7dglHPQynAIOSDj/m3LJE351cnN6KYvaBC1WH8OxY2eL7H6bOg8lTe8iaZk+8LsqlWpIziIdQVvlVOeLxg1++0KOO6M12wiP3V+qe3uMqFNnZprPrJHZnRIG4OXcIJGbUgbdpzr7D+K1/llZBECAwEAAaNQME4wHQYDVR0OBBYEFHGZjXwNnbTg1TLFMLhxUiN6cHJvMB8GA1UdIwQYMBaAFHGZjXwNnbTg1TLFMLhxUiN6cHJvMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAC0pNiSx/U9Kz7NPgGbSHRcnr+j7Uhu+Gl6U9K7GPyEGG986pYpqvuJ8U/us/RTJhDMVPWfqdMPxXpypvcnYi7DVK8x7tNZEq7uHK4mPpRqSxwtUcjziBSZDZyTkiNbueyw4/NdwIGJlHmFQyOHR2elvaO3yPORXeH89UEG7MdrY/U0pNriQcngfKFnlMa9vnn+gnddCtXQQA2zhspkS31Vjj8+tGEmAMEnNZyAU8inSoT2tSsUT27jxYQk3yqVZAKa4XSs+ssd9vDZn6MbZuyDpSvqLKiVJB6i03THJLJ1I5IDFMd8R+WAuv8bJCY6bOp1NVDUu9Sz7iOjRCG7HLDA=&lt;/ds:X509Certificate&gt;
          &lt;/ds:X509Data&gt;
        &lt;/ds:KeyInfo&gt;
      &lt;/md:KeyDescriptor&gt;
      &lt;md:KeyDescriptor use=&quot;encryption&quot;&gt;
        &lt;ds:KeyInfo xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
          &lt;ds:X509Data&gt;
            &lt;ds:X509Certificate&gt;MIIDYTCCAkmgAwIBAgIBADANBgkqhkiG9w0BAQsFADBLMQswCQYDVQQGEwJVUzELMAkGA1UECAwCTUkxEjAQBgNVBAcMCUFubiBBcmJvcjEbMBkGA1UECgwSRHVvIFNlY3VyaXR5LCBJbmMuMB4XDTE4MDMwNjIwNTI0MFoXDTI4MDMwMzIwNTI0MFowSzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk1JMRIwEAYDVQQHDAlBbm4gQXJib3IxGzAZBgNVBAoMEkR1byBTZWN1cml0eSwgSW5jLjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALb+uWJmWMxAky+MgUDR9u5Ho/Wrx3V/zCAcoAN3dWnEwKYNJafLkjy+cyhrH6VkIpi1olcvrUXJ2wSXU8AZ93H4FCJz0gkiWyDOb5BIbd4tsTzJ6Y1ROGwv0jA2z4vinWd7LrptbQTQ2pOwffEpgG8A9BmLnxp7VxKWmvAPu//G+b2znwkvrRfq+gP1i8FOzbvbj7dglHPQynAIOSDj/m3LJE351cnN6KYvaBC1WH8OxY2eL7H6bOg8lTe8iaZk+8LsqlWpIziIdQVvlVOeLxg1++0KOO6M12wiP3V+qe3uMqFNnZprPrJHZnRIG4OXcIJGbUgbdpzr7D+K1/llZBECAwEAAaNQME4wHQYDVR0OBBYEFHGZjXwNnbTg1TLFMLhxUiN6cHJvMB8GA1UdIwQYMBaAFHGZjXwNnbTg1TLFMLhxUiN6cHJvMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAC0pNiSx/U9Kz7NPgGbSHRcnr+j7Uhu+Gl6U9K7GPyEGG986pYpqvuJ8U/us/RTJhDMVPWfqdMPxXpypvcnYi7DVK8x7tNZEq7uHK4mPpRqSxwtUcjziBSZDZyTkiNbueyw4/NdwIGJlHmFQyOHR2elvaO3yPORXeH89UEG7MdrY/U0pNriQcngfKFnlMa9vnn+gnddCtXQQA2zhspkS31Vjj8+tGEmAMEnNZyAU8inSoT2tSsUT27jxYQk3yqVZAKa4XSs+ssd9vDZn6MbZuyDpSvqLKiVJB6i03THJLJ1I5IDFMd8R+WAuv8bJCY6bOp1NVDUu9Sz7iOjRCG7HLDA=&lt;/ds:X509Certificate&gt;
          &lt;/ds:X509Data&gt;
        &lt;/ds:KeyInfo&gt;
      &lt;/md:KeyDescriptor&gt;
      &lt;md:SingleLogoutService Binding=&quot;urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect&quot; Location=&quot;https://dag.corp.imvu.com/dag/saml2/idp/SingleLogoutService.php?ReturnTo=https://dag.corp.imvu.com/dag/module.php/duosecurity/logout.php&quot;/&gt;
      &lt;md:SingleLogoutService Binding=&quot;urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST&quot; Location=&quot;https://dag.corp.imvu.com/dag/saml2/idp/SingleLogoutService.php?ReturnTo=https://dag.corp.imvu.com/dag/module.php/duosecurity/logout.php&quot;/&gt;
      &lt;md:NameIDFormat&gt;urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified&lt;/md:NameIDFormat&gt;
      &lt;md:NameIDFormat&gt;urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress&lt;/md:NameIDFormat&gt;
      &lt;md:NameIDFormat&gt;urn:oasis:names:tc:SAML:2.0:nameid-format:persistent&lt;/md:NameIDFormat&gt;
      &lt;md:NameIDFormat&gt;urn:oasis:names:tc:SAML:2.0:nameid-format:transient&lt;/md:NameIDFormat&gt;
      &lt;md:NameIDFormat&gt;urn:oasis:names:tc:SAML:1.1:nameid-format:WindowsDomainQualifiedName&lt;/md:NameIDFormat&gt;
      &lt;md:NameIDFormat&gt;urn:oasis:names:tc:SAML:2.0:nameid-format:kerberos&lt;/md:NameIDFormat&gt;
      &lt;md:SingleSignOnService Binding=&quot;urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect&quot; Location=&quot;https://dag.corp.imvu.com/dag/saml2/idp/SSOService.php&quot;/&gt;
      &lt;md:SingleSignOnService Binding=&quot;urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST&quot; Location=&quot;https://dag.corp.imvu.com/dag/saml2/idp/SSOService.php&quot;/&gt;
      &lt;md:SingleSignOnService Binding=&quot;urn:oasis:names:tc:SAML:2.0:bindings:SOAP&quot; Location=&quot;https://dag.corp.imvu.com/dag/saml2/idp/SSOService.php&quot;/&gt;
    &lt;/md:IDPSSODescriptor&gt;
    &lt;/md:EntityDescriptor&gt;</xml>
        <url></url>
        <period>0</period>
      </idpMetadataConfiguration>
    </securityRealm>

###  JCasC configuration for new deployment jenkins from the scratch.
 # JCasC:
 #   enabled: true
 #   ConfigScripts:
 #     matrix-auth: |
 #       jenkins:
 #         authorizationStrategy:
 #           projectMatrix:
 #             grantedPermissions:
 #             - "Overall/Administer:mklipikov@imvu.com"
 #             - "Overall/Administer:ahart@imvu.com"
 #             - "Overall/Administer:restrugo@imvu.com"
 #             - "Overall/Administer:eworth@imvu.com"
 #             - "Overall/Administer:dmercredi@imvu.com"
 #             - "Overall/Administer:akurochka@imvu.com"
 #             - "Overall/Read:it-admin@imvu.com"
 #             - "Overall/Read:mklipikov@imvu.com"
 #             - "Overall/Read:ahart@imvu.com"
 #             - "Overall/Read:restrugo@imvu.com"
 #             - "Overall/Read:eworth@imvu.com"
 #             - "Overall/Read:dmercredi@imvu.com"
 #             - "Overall/Read:akurochka@imvu.com"
 #     credentials-settings: |
 #       credentials:
 #        system:
 #          domainCredentials:
 #            - credentials:
 #                - string:
 #                     scope: GLOBAL
 #                     id: slack-token
 #                     secret: '${SLACK_TOKEN}'
 #                     description: Slack token
 #
 #     slack-settings: |
 #      unclassified:
 #        slackNotifier:
 #          teamDomain: <your-slack-workspace-name>
 #          tokenCredentialId: slack_token
 #
 #
 #   Sidecars:
 #     configAutoReload:
 #       enabled: true
 #       image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-cicd/jenkins-master-jcaasc-sidecar:0.0.2

### Plugin configuration
  installPlugins:
    - workflow-aggregator:2.6
    - workflow-job:2.39
    - workflow-basic-steps:2.20
    - workflow-scm-step:2.11
    - workflow-api:2.40
    - workflow-cps:2.80
    - workflow-durable-task-step:2.35
    - workflow-cps-global-lib:2.16
    - workflow-step-api:2.21
    - pipeline-graph-analysis:1.10
    - pipeline-model-definition:1.7.0
    - pipeline-model-extensions:1.7.0
    - pipeline-model-api:1.7.0
    - pipeline-stage-tags-metadata:1.7.0
    - external-monitor-job:1.7
    - durable-task:1.34
    - token-macro:2.12
    - trilead-api:1.0.8
    - branch-api:2.5.6
    - credentials-binding:1.23
    - credentials:2.3.9
    - script-security:1.73
    - git:4.3.0
    - git-client:3.3.0
    - scm-api:2.6.3
    - jackson2-api:2.10.0
    - greenballs:1.15
    - locale:1.4
    - show-build-parameters:1.0
    - extra-columns:1.22
    - build-timeout:1.20
    - sse-gateway:1.23
    - ant:1.11
    - uno-choice:2.3
    - scriptler:3.1
    - antisamy-markup-formatter:2.0
    - command-launcher:1.4
    - prometheus:2.0.7
    - timestamper:1.11.5
# Notification plugins
    - slack:2.28
    - jira:3.1.1
# Manage Slave Nodes
    - ssh-slaves:1.30.2
    - ssh-credentials:1.17.3
    - pam-auth:1.6
    - kubernetes:1.26.1
    - resource-disposer:0.13
    - windows-slaves:1.5
    - p4:1.11.2
    - prqa-plugin:3.3.3
# Auth and authz
    - matrix-auth:2.6.1
    - saml:1.1.2
    - ldap:1.20
# Xcode iOS
    - xcode-plugin:2.0.12
# Cleanup workspace for jobs on Master
    - ws-cleanup:0.37
# BO-components-and-dependencies
    - blueocean:1.21.0
# Tests heplers plugins
    - junit:1.29
    - htmlpublisher:1.23
# Vault plugins
    - hashicorp-vault-pipeline:1.3
    - hashicorp-vault-plugin:2.5.0
    - mask-passwords:2.13

### Config Master Pod
  servicePort: 8080
  serviceType: NodePort
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.withme.com
    path: /

### Config for jenkins slave pod
agent:
  enabled: true
  image: "407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-cicd/jenkins-slave"
  imageTag: "3.27-1"
  #autoadjust agent resources limits
  resources:
    requests:
      cpu: null
      memory: null
    limits:
      cpu: null
      memory: null

#to allow jenkins create slave pods
rbac:
  create: true

persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires Persistence.Enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # ExistingClaim:
  ## jenkins data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # StorageClass: "-"
  annotations: {}
  accessMode: ReadWriteOnce
  size: 32Gi
  volumes:
  #  - name: nothing
  #    emptyDir: {}
  mounts:
  #  - mountPath: /var/nothing
  #    name: nothing
  #    readOnly: true
