{
 "title": "Top-Level",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Online",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(connection_manager_users_online{application='connection-manager'})",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "Cloud-Hosted Game Servers by State (tier game_server)",
   "type": "graph",
   "description": "The cloud hosted game servers for the game_server tier.",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size{type=\"CLOUD_HOSTED_GAME_SERVER\", tier=\"game_server\", org=\"withme\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Microservice pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_tier=\"microservice\"})",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Non-working services",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar(count(\n  sum by (label_app) (\n    kube_pod_status_phase{phase=\"Running\"}\n    * on (pod) group_left(label_app)\n    kube_pod_labels{label_tier=\"microservice\"}\n  ) == 0\n))"
    }
   ]
  },
  {
   "title": "Failed logins",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"account-manager\",uri=\"/user/v1/login\",status=~\"[4-5][0-9]*\"}[10m]))"
    }
   ]
  },
  {
   "title": "Tiers",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "expr": "count(kube_node_labels) by (label_prod_1_tier)"
    },
    {
     "expr": "avg(count by (node, label_prod_1_tier) (\n  (node_namespace_pod:kube_pod_info:)\n  * on (node) group_left(label_prod_1_tier)\n  (kube_node_labels)\n)) by (label_prod_1_tier)"
    },
    {
     "expr": "max(count by (node, label_prod_1_tier) (\n  (node_namespace_pod:kube_pod_info:)\n  * on (node) group_left(label_prod_1_tier)\n  (kube_node_labels)\n)) by (label_prod_1_tier)"
    }
   ]
  },
  {
   "title": "Online in 3D space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_session_users_count) by (tier)",
     "legendFormat": "{{tier}}"
    }
   ]
  },
  {
   "title": "Cloud-Hosted Game Servers by State (tier game_server2)",
   "type": "graph",
   "description": "The cloud hosted game servers for the game_server2 tier.",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size{type=\"CLOUD_HOSTED_GAME_SERVER\", tier=\"game_server2\", org=\"withme\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Microservice pods status",
   "type": "table-old",
   "gridPos": { "h": 21, "w": 7, "x": 17, "y": 13 },
   "targets": [
    {
     "expr": "sum by (label_app) (\n\tkube_pod_status_phase{phase=\"Running\"}\n\t* on (pod) group_left(label_app)\n\tkube_pod_labels{label_tier=\"microservice\"}\n)"
    },
    {
     "expr": "sum by (label_app) (\n\tkube_pod_status_phase{phase=\"Pending\"}\n\t* on (pod) group_left(label_app)\n\tkube_pod_labels{label_tier=\"microservice\"}\n)"
    },
    {
     "expr": "sum by (label_app) (\n\tkube_pod_status_phase{phase=\"Failed\"}\n\t* on (pod) group_left(label_app)\n\tkube_pod_labels{label_tier=\"microservice\"}\n)"
    }
   ]
  },
  {
   "title": "Microservice HTTP requests",
   "type": "table-old",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri!~\"/actuator/.*\",uri!~\"/health/.*\"}[5m]) * 1000 > 0) by (service) / on (service) sum(rate(http_server_requests_seconds_count{uri!~\"/actuator/.*\",uri!~\"/health/.*\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "max(max_over_time(http_server_requests_seconds_max{uri!~\"/actuator/.*\",uri!~\"/health/.*\"}[5m]) * 1000) by (service)",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4[0-9]*\", uri!~\"/actuator/.*\",uri!~\"/health/.*\"}[5m]) * 60) by (service)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5[0-9]*\", uri!~\"/actuator/.*\",uri!~\"/health/.*\"}[5m]) * 60) by (service)"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\"/actuator/.*\",uri!~\"/health/.*\"}[5m]) * 60) by (service)"
    }
   ]
  },
  {
   "title": "Microservice HTTP requests (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\"/actuator/.*\",uri!~\"/health/.*\"}[5m]) * 60) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Microservice HTTP error counters (per minute)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4[0-9]*\",uri!~\"/actuator/.*\",uri!~\"/health/.*\"}[5m]) * 60) by (service)",
     "legendFormat": "{{service}} 4xx"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5[0-9]*\",uri!~\"/actuator/.*\",uri!~\"/health/.*\"}[5m]) * 60) by (service)",
     "legendFormat": "{{service}} 5xx"
    }
   ]
  },
  {
   "title": "Microservice requests duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri!~\"/actuator/.*\",uri!~\"/health/.*\"}[5m])) by (service) / on (service) sum(rate(http_server_requests_seconds_count{uri!~\"/actuator/.*\",uri!~\"/health/.*\"}[5m])) by (service)",
     "legendFormat": "{{service}} average"
    },
    {
     "expr": "max(http_server_requests_seconds_max{uri!~\"/actuator/.*\",uri!~\"/health/.*\"}) by (service)",
     "legendFormat": "{{service}} max"
    }
   ]
  }
 ]
}