"""empty message

Revision ID: dde1e11fcf17
Revises: 5b5cfcb6df33
Create Date: 2021-05-30 18:59:35.590771

"""

# revision identifiers, used by Alembic.
revision = 'dde1e11fcf17'
down_revision = '5b5cfcb6df33'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_repos',
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('repo_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], )
    )
    op.drop_constraint('service_repo_id_fkey', 'service', type_='foreignkey')
    op.drop_column('service', 'repo_id')
    op.drop_column('service', 'scm_url')
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('scm_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('service', sa.Column('repo_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('service_repo_id_fkey', 'service', 'repo', ['repo_id'], ['id'])
    op.drop_table('services_repos')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass