#
# etcd 3 member cluster
#
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "etcd-cluster"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "3.3.12"
  repository: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/etcd
  pod:
    labels:
      component: etcd-cluster
