org             = "withme"
dept            = "services"
environment     = "prod"
role            = "automation"
config          = "default"
region          = "us-west-2"
provider_region = "us-west-2"
tfstate_region = "us-west-2"
