AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Elasticsearch CloudFormation template'

#-------------------------------------------------------------------#
################################ CloudFormation template parameters #

Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC of the k8s worker instances

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: SubnetId for assosiation AWS ES VPC Endpoint

  EC2SecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Specifies SG group ID that allowed to communicate with AWS Elasticsearch.
    ConstraintDescription: "Please provide valid ids for the security group(s)."

  DomainName:
    Type: String
    Description: Name for ElasticsearchDomain Cluster

  ESsecurityGroupName:
    Type: String
    Description: 'Name of security group for Elasticsearch'

  ESsecurityGroupPort:
    Type: Number
    Description: 'Port allowed in Inbound ports of ESsecurityGroup'

  DedicatedMasterCount:
    Type: String
    Default: ''
    Description: The number of instances to use for the master node. If you specify this property, you must specify true for the DedicatedMasterEnabled property.

  DedicatedMaster:
    Type: String
    AllowedValues: 
      - true
      - false
      - ''
    Default: ''
    Description: Use dedicated master for ES cluster.

  DedicatedMasterType:
    Type: String
    AllowedValues:
      - t2.small.elasticsearch
      - t2.medium.elasticsearch
      - m3.medium.elasticsearch
      - m3.large.elasticsearch
      - m3.xlarge.elasticsearch
      - m3.2xlarge.elasticsearch
      - m4.large.elasticsearch
      - m4.xlarge.elasticsearch
      - m4.2xlarge.elasticsearch
      - m4.4xlarge.elasticsearch
      - m4.10xlarge.elasticsearch
      - c4.large.elasticsearch
      - c4.xlarge.elasticsearch
      - c4.2xlarge.elasticsearch
      - c4.4xlarge.elasticsearch
      - c4.8xlarge.elasticsearch
      - r3.large.elasticsearch
      - r3.xlarge.elasticsearch
      - r3.2xlarge.elasticsearch
      - r3.4xlarge.elasticsearch
      - r3.8xlarge.elasticsearch
      - r4.large.elasticsearch
      - r4.xlarge.elasticsearch
      - r4.2xlarge.elasticsearch
      - ''
    Default: ''
    ConstraintDescription: Must be a valid AWS ES instance type
    Description: Type of AWS ES instance for Dedicated master-s.

  ZoneAwareness:
    Type: String
    Description: Indicates whether to enable zone awareness for the Amazon ES domain. When you enable zone awareness, Amazon ES allocates the nodes and replica index shards that belong to a cluster across two Availability Zones (AZs) in the same region to prevent data loss and minimize downtime in the event of node or data center failure.

  AvailabilityZoneCount:
    Type: Number
    Description: If you enabled multiple Availability Zones (AZs), the number of AZs that you want the domain to use.


  ESversion:
    Type: String
    AllowedValues:
      - 7.1
      - 6.8
      - 6.7
      - 6.5
      - 6.4
      - 6.3
      - 6.2
    Description: Elasticsearch Version

  ESDataInstanceCount:
    Type: Number
    Description: The number of data nodes for your cluster

  ESDataInstanceType:
    Type: String
    AllowedValues:
      - t2.small.elasticsearch
      - t2.medium.elasticsearch
      - m3.medium.elasticsearch
      - m3.large.elasticsearch
      - m3.xlarge.elasticsearch
      - m3.2xlarge.elasticsearch
      - m4.large.elasticsearch
      - m4.xlarge.elasticsearch
      - m4.2xlarge.elasticsearch
      - m4.4xlarge.elasticsearch
      - m4.10xlarge.elasticsearch
      - c4.large.elasticsearch
      - c4.xlarge.elasticsearch
      - c4.2xlarge.elasticsearch
      - c4.4xlarge.elasticsearch
      - c4.8xlarge.elasticsearch
      - r3.large.elasticsearch
      - r3.xlarge.elasticsearch
      - r3.2xlarge.elasticsearch
      - r3.4xlarge.elasticsearch
      - r3.8xlarge.elasticsearch
      - r4.large.elasticsearch
      - r4.xlarge.elasticsearch
      - r4.2xlarge.elasticsearch
    ConstraintDescription: Must be a valid AWS ES instance type
    Description: Type of AWS ES instance for the Data instances.

  ESDataInstanceVolumeSize:
    Type: Number
    ConstraintDescription: Must be a valid for choosed AWS ES instance type.
    Description: Size for node volumes GB


#-------------------------------------------------------------------#
############################# AWS Elasticsearch Template Conditions #
Conditions:
  CreateESmasters: !Equals [ !Ref DedicatedMaster, true ]

Resources:
#-------------------------------------------------------------------#
################################## AWS Elasticsearch Security Group #
  awsESdomainSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref ESsecurityGroupName
      GroupDescription: Allow communication to AWS Elasticsearch
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ESsecurityGroupPort
          ToPort: !Ref ESsecurityGroupPort
          SourceSecurityGroupId: !Ref EC2SecurityGroupID
      Tags:
        - Key: Name
          Value: !Ref ESsecurityGroupName

#-------------------------------------------------------------------#
########################################## AWS Elasticsearch Domain #
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    DependsOn: awsESdomainSG
    Properties:
      DomainName: !Ref DomainName
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled:
         !If [ CreateESmasters, !Ref DedicatedMaster, !Ref "AWS::NoValue" ] 
        DedicatedMasterCount: 
         !If [ CreateESmasters, !Ref DedicatedMasterCount, !Ref "AWS::NoValue" ] 
        DedicatedMasterType: 
          !If [ CreateESmasters, !Ref DedicatedMasterType, !Ref "AWS::NoValue" ] 
        InstanceCount: !Ref ESDataInstanceCount
        InstanceType: !Ref ESDataInstanceType
        ZoneAwarenessEnabled: !Ref ZoneAwareness
        ZoneAwarenessConfig:
          AvailabilityZoneCount: !Ref AvailabilityZoneCount
      ElasticsearchVersion: !Ref ESversion
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: !Ref ESDataInstanceVolumeSize
        VolumeType: "gp2"
      SnapshotOptions:
        AutomatedSnapshotStartHour: "0"
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: "true"
      Tags:
        - Key: Domain
          Value: !Ref DomainName
      VPCOptions:
        SubnetIds: !Ref Subnets
        SecurityGroupIds:
          - !Ref awsESdomainSG

#-------------------------------------------------------------------#
################################################## Template Outputs #
Outputs:
  DomainArn:
    Value: !GetAtt ElasticsearchDomain.DomainArn

  DomainEndpoint:
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint

  ElasticsearchSGid:
    Value: !Ref awsESdomainSG