AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  EC2roleName:
    Description: Name for EC2 Role
    Type: String

  ASroleName:
    Description: Name for UPR Autoscaling Role
    Type: String

Resources: 
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref EC2roleName
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ec2.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: upr-ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: ['ecs:CreateCluster', 'ecs:DeregisterContainerInstance', 'ecs:DiscoverPollEndpoint',
              'ecs:Poll', 'ecs:RegisterContainerInstance', 'ecs:StartTelemetrySession',
              'ecs:Submit*', 'logs:CreateLogStream', 'logs:PutLogEvents', "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability", "ecr:GetDownloadUrlForLayer", "ecr:BatchGetImage"]
            Resource: '*'
      - PolicyName: ssm
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ssmmessages:*' # SSM Agent by https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up-messageAPIs.html
                - 'ssm:UpdateInstanceInformation' # SSM agent by https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up-messageAPIs.html
                - 'ec2messages:*' # SSM Session Manager by https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up-messageAPIs.html
                - 'ssm:ListInstanceAssociations' # SSM Session Manager by https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up-messageAPIs.html
              Resource: 
              - '*'

  AutoscalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ASroleName
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [application-autoscaling.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: service-autoscaling
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: ['application-autoscaling:*', 'cloudwatch:DescribeAlarms', 'cloudwatch:PutMetricAlarm',
              'ecs:DescribeServices', 'ecs:UpdateService']
            Resource: '*'

Outputs:
  EC2roleNAME:
    Description: EC2 Role name 
    Value: !Ref EC2Role

  EC2roleARN:
    Description: EC2 Role ARN 
    Value: !GetAtt EC2Role.Arn

  ASroleNAME:
    Description: AutoscalingRole name
    Value: !Ref AutoscalingRole

  ASroleARN:
    Description: ARN of AutoscalingRole for UPR
    Value: !GetAtt AutoscalingRole.Arn