template_path: aws-cloudfront.yaml

parameters:
  DNSName: 'api.withme.com'
  OriginPath: ''
  OriginProtocolPolicy: 'https-only'
  OriginKeepaliveTimeout: '60'
  OriginReadTimeout: '30'
  ViewerProtocolPolicy: 'redirect-to-https'
  PriceClass: 'PriceClass_100'
  HTTPPort: '80'
  HTTPSPort: '443'
  DistributionConfigEnabled: 'true'
  ForwardedValuesQueryString: 'false'
  AlternateDomainNames: 'content.withme.com'
  AcmCertificateArn: 'arn:aws:acm:us-east-1:407733091588:certificate/0e73e0e7-cef5-44fd-acca-c27d2a9ff728'
  SslSupportMethod: 'sni-only'
  MinimumProtocolVersion: 'TLSv1'
