AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS DynamoDB, AWS KMS, AWS IAM Policies for Hashicorp Vault'

Parameters:

  NodeInstanceRoleName:
    Type: String
    Default: env-cicd-cicdUtil-1O9RL11256YZE-NodeInstanceRole-3ERU7WZVH3EF
    Description: EKS Worker nodes Role Name

  NodeInstanceRoleARN:
    Type: String
    Default: arn:aws:iam::407733091588:role/env-cicd-cicdUtil-1O9RL11256YZE-NodeInstanceRole-3ERU7WZVH3EF
    Description: EKS Worker nodes Role ARN

  DynamoDBtableName:
    Type: String
    Default: vault_data
    Description: Name for Vault DynamoDB table

Resources:

  tableVaultData:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref DynamoDBtableName
      AttributeDefinitions:
        - AttributeName: Path
          AttributeType: S
        - AttributeName: Key
          AttributeType: S
      KeySchema:
        - AttributeName: Path
          KeyType: HASH
        - AttributeName: Key
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      Tags:
      - Key: Name
        Value: vault-dynamodb-table
      - Key: Environment
        Value: All

  KMSvault:
    Type: AWS::KMS::Key
    Properties:
      Description: "Encrypt/Decrypt and Unseal for Hashicorp Vault"
      KeyPolicy:
        Version: 2012-10-17
        Id: hashicorp-vault-key
        Statement:
          - Sid: "Allow administration of the key"
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:*"
            Resource: "*"
          - Sid: "Allow use of the key"
            Effect: Allow
            Principal:
              AWS: !Ref NodeInstanceRoleARN
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:DescribeKey"
            Resource: "*"

  DynamoDBpolicy:
    Type: AWS::IAM::Policy
    DependsOn: KMSvault
    Properties:
      PolicyName: "DynamoDBreadWrite"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "dynamodb:DescribeLimits"
              - "dynamodb:DescribeTimeToLive"
              - "dynamodb:ListTagsOfResource"
              - "dynamodb:DescribeReservedCapacityOfferings"
              - "dynamodb:DescribeReservedCapacity"
              - "dynamodb:ListTables"
              - "dynamodb:BatchGetItem"
              - "dynamodb:BatchWriteItem"
              - "dynamodb:CreateTable"
              - "dynamodb:DeleteItem"
              - "dynamodb:GetItem"
              - "dynamodb:GetRecords"
              - "dynamodb:PutItem"
              - "dynamodb:Query"
              - "dynamodb:UpdateItem"
              - "dynamodb:Scan"
              - "dynamodb:DescribeTable"
            Resource: "arn:aws:dynamodb:us-west-2:*:*"
            Condition:
              IpAddress:
                aws:SourceIp:
                  - "54.148.188.220/32"
                  - "52.89.141.126/32"
                  - "54.148.200.76/32"
      Roles:
        - !Ref NodeInstanceRoleName

  KMSpolicy:
    Type: AWS::IAM::Policy
    DependsOn: tableVaultData
    Properties:
      PolicyName: "KMSvaultRead"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "kms:Decrypt"
              - "kms:Encrypt"
              - "kms:DescribeKey"
            Resource: "arn:aws:kms:us-west-2:*:key/hashicorp-vault-key"
            Condition:
              IpAddress:
                aws:SourceIp:
                  - "54.148.188.220/32"
                  - "52.89.141.126/32"
                  - "54.148.200.76/32"
      Roles:
        - !Ref NodeInstanceRoleName

Outputs:
  KMSvaultKeyID:
    Description: KMS Key ID
    Value: !Ref KMSvault

  DynamoDBtableName:
    Description: Vault DynamoDB table name.
    Value: !Ref tableVaultData
