---
AWSTemplateFormatVersion: 2010-09-09
Description: Custom IAM Policies for CICD NodeGroup IAM Role

Parameters:

  PolicyNameDynamoDB:
    Description: DynamoDB inline IAM Policy name
    Type: String

  PolicyNameKMS:
    Description: KMS inline IAM Policy name
    Type: String

  RoleName:
    Description: Worker-group IAM Role name that will use that IAM policy
    Type: String

Resources:

  DynamoDBpolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref PolicyNameDynamoDB
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "dynamodb:DescribeLimits"
              - "dynamodb:DescribeTimeToLive"
              - "dynamodb:ListTagsOfResource"
              - "dynamodb:DescribeReservedCapacityOfferings"
              - "dynamodb:DescribeReservedCapacity"
              - "dynamodb:ListTables"
              - "dynamodb:BatchGetItem"
              - "dynamodb:BatchWriteItem"
              - "dynamodb:CreateTable"
              - "dynamodb:DeleteItem"
              - "dynamodb:GetItem"
              - "dynamodb:GetRecords"
              - "dynamodb:PutItem"
              - "dynamodb:Query"
              - "dynamodb:UpdateItem"
              - "dynamodb:Scan"
              - "dynamodb:DescribeTable"
            Resource: "arn:aws:dynamodb:us-west-2:*:*"
            Condition:
              IpAddress:
                aws:SourceIp:
                  - "54.148.188.220/32"
                  - "52.89.141.126/32"
                  - "54.148.200.76/32"
      Roles:
        - !Ref RoleName

  KMSpolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref PolicyNameKMS
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "kms:Decrypt"
              - "kms:Encrypt"
              - "kms:DescribeKey"
            Resource: "arn:aws:kms:us-west-2:*:key/hashicorp-vault-key"
            Condition:
              IpAddress:
                aws:SourceIp:
                  - "54.148.188.220/32"
                  - "52.89.141.126/32"
                  - "54.148.200.76/32"
      Roles:
        - !Ref RoleName

Outputs:

  KMSpolicyName:
    Description: KMS Inline policy name
    Value: !Ref KMSpolicy

  DynamoDBpolicyName:
    Description: DynamoDB Inline policy name
    Value: !Ref DynamoDBpolicy
