######################################################
# metadata
####

# logical environment, not any specific place or piece of infrastructure
environment: "int"
region: "us-west-2"
# used for sceptre and uniquely identifying stack
project_code: "astral"

# our "app name"
game_server_name: "game-server"
######################################################


######################################################
# Infrastructure deployment coordinates targeting 
####
deployment_target: "int-2"


######################################################

######################################################
# GameLift fleet configuration
####
fleet_type: "ON_DEMAND"
new_game_sessions_per_creator: "10"
policy_period_in_minutes: "60"
max_size: "1"
min_size: "0"
new_game_session_protection_policy: "FullProtection"
ec2_instance_type: "m5.large"
instance_count: "1"
######################################################

######################################################
# GameLift default alias configuration
####
routing_strategy_type: "SIMPLE"
message: "w00t! - alias"
######################################################

