template_path: upr-route53.yaml

parameters:
# VPC ID in which that Private Route53 HostedZone will work.
# Quantity of HostedZone VPC's can be increased for serving more VPC's even in different regions. 
  vpcID: !stack_output_external int-2-eks-vpc::VpcId
# DNS name for Private HostedZone
  HostedZoneName: int-2.etcd.upr