---
## main configuration for "mongors" Replica Set 
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongors
  namespace: database
spec:
  version: "4.1.7-v1"
  replicas: 3
  replicaSet:
    name: rs0
  storageType: "Durable"
  storage:
    storageClassName: "gp2"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  terminationPolicy: DoNotTerminate
  podTemplate:
    spec:
      metadta:
        iam.amazonaws.com/role: int2-mongors-s3-rw
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: int-2-tier
                operator: In
                values:
                - mongodb
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: kubedb.com/name
                  operator: In
                  values:
                  - mongo-rs
              topologyKey: kubernetes.io/hostname
  updateStrategy:
    type: RollingUpdate
# Sceduled Backup Config for "mongors" 
  backupSchedule:
    cronExpression: "@every 24h"
    podTemplate:
      metadata:
        annotations:
          iam.amazonaws.com/role: int2-mongors-s3-rw
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: int-2-tier
                  operator: In
                  values:
                  - mongodb
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
    podVolumeClaimSpec:
      storageClassName: "gp2"
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
## Configure AWS S3 Storage for storing "mongors" Backups
    s3:
      endpoint: s3.amazonaws.com
      bucket: int2-kubedb-backups-us-west-2-407733091588
      