{
 "title": "Game Server Managers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cloud-Hosted Game Servers by State (org withmedev)",
   "type": "graph",
   "description": "The cloud hosted game servers for the withmedev organization.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size{type=\"CLOUD_HOSTED_GAME_SERVER\", org=\"withmedev\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cloud-Hosted Game Servers by State (org withmeqa)",
   "type": "graph",
   "description": "The cloud hosted game servers for the withmeqa organization.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size{type=\"CLOUD_HOSTED_GAME_SERVER\", org=\"withmeqa\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cloud-Hosted Game Servers by State (org withmedev2)",
   "type": "graph",
   "description": "Displays the states for all the cloud-hosted game severs in the withmedev2 organization managed by the Game Server Manager",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Cloud-Hosted Servers" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size{type=\"CLOUD_HOSTED_GAME_SERVER\", org=\"withmedev2\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cloud-Hosted Game Servers by State (org withmeqa2)",
   "type": "graph",
   "description": "The cloud hosted game servers for the withmeqa2 organization.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size{type=\"CLOUD_HOSTED_GAME_SERVER\", org=\"withmeqa2\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cloud-Hosted Game Servers by State (org withmedev3)",
   "type": "graph",
   "description": "Displays the states for all the cloud-hosted game severs in the withmedev3 organization managed by the Game Server Manager",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Cloud-Hosted Servers" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size{type=\"CLOUD_HOSTED_GAME_SERVER\", org=\"withmedev3\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cloud-Hosted Game Servers by State (org withmeperf)",
   "type": "graph",
   "description": "Displays the states for all the cloud-hosted game severs in the withmeperf organization managed by the Game Server Manager",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Cloud-Hosted Servers" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size{type=\"CLOUD_HOSTED_GAME_SERVER\", org=\"withmeperf\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cloud-Hosted Game Servers by State (org withmedev4)",
   "type": "graph",
   "description": "Displays the states for all the cloud-hosted game severs in the withmedev4 organization managed by the Game Server Manager",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Cloud-Hosted Servers" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size{type=\"CLOUD_HOSTED_GAME_SERVER\", org=\"withmedev4\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Users In Game Sessions by Organization",
   "type": "graph",
   "description": "Plots the number of users in game sessions by organization",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_session_users_count) by (org)",
     "legendFormat": "{{org}}"
    }
   ]
  },
  {
   "title": "Game Server State Table Process Events Time",
   "type": "graph",
   "description": "The average and maximum duration for processing game server state table events.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(game_server_state_table_process_event_timer_seconds_sum[1m])/rate(game_server_state_table_process_event_timer_seconds_count[1m]))",
     "legendFormat": "MAX"
    },
    {
     "expr": "sum(rate(game_server_state_table_process_event_timer_seconds_sum[1m]))/sum(rate(game_server_state_table_process_event_timer_seconds_count[1m]))",
     "legendFormat": "AVE"
    }
   ]
  },
  {
   "title": "Game Servers by Hosted Type",
   "type": "graph",
   "description": "The total number of game servers registered and grouped according to how they are hosted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Game Server State Table Queue Size",
   "type": "graph",
   "description": "The size of the game server state table queue for each Pod.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_state_table_queue_size) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}