template_path: worker-nodes.yaml

parameters:
  NodeSecurityGroup: !stack_output us-west-2/eks/cluster.yaml::NodeSecurityGroup
  ClusterName: !resolver_yaml config/defaults.yml::EKS.ClusterName
  NodeImageId: !resolver_yaml config/defaults.yml::EKS.NodeImageId
  VpcId: !stack_output us-west-2/network/vpc.yaml::VpcId
  Subnets:
    - !stack_output us-west-2/network/vpc.yaml::PrivSubnet01ID
    - !stack_output us-west-2/network/vpc.yaml::PrivSubnet02ID
  KeyName: kubernetes-int-1-key-pair
  NodeInstanceType: t3.medium
  NodeAutoScalingGroupMinSize: '7'
  NodeAutoScalingGroupMaxSize: '12'
  NodeAutoScalingGroupDesiredCapacity: '10'
  NodeVolumeSize: '64'
  BootstrapArguments: "--kubelet-extra-args --node-labels=nodeClass=service-small"
  NodeGroupName: int-1-nodes

sceptre_user_data:
  NodeRoleArn: "- rolearn: NodeRoleArn\n  username: system:node:{{ '{{EC2PrivateDNSName}}' }}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"
  NodeGroupName: "worker-nodes"
  FetchSavePath: !resolver_yaml config/defaults.yml::FetchSavePath
  
hooks:
  after_create:
    - !hook_eks ConfigMap::apply::aws-auth-append
    - !hook_eks ConfigMap::fetch::aws-auth@kube-system
  before_delete:
    - !hook_eks ConfigMap::delete::aws-auth@kube-system
