"""empty message

Revision ID: 067f8b64c38a
Revises: 197b50f32188
Create Date: 2026-01-11 13:48:21.232339

"""

# revision identifiers, used by Alembic.
revision = '067f8b64c38a'
down_revision = '197b50f32188'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_current_release',
                    sa.Column('deployment_id', sa.String(), nullable=False),
                    sa.Column('release_id', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
                    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
                    sa.PrimaryKeyConstraint('deployment_id', 'release_id')
                    )
    op.create_index('ix_deployment_current_release_release_id', 'deployment_current_release', ['release_id'], unique=False)
    op.drop_index('ix_deployment_current_release_id', table_name='deployment')
    op.drop_column('deployment', 'current_release_id')
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('current_release_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_deployment_current_release_id', 'deployment', ['current_release_id'], unique=False)
    op.drop_index('ix_deployment_current_release_release_id', table_name='deployment_current_release')
    op.drop_table('deployment_current_release')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass