"""empty message

Revision ID: starting_point
Revises: None
Create Date: 2023-08-12 10:15:42.601509

"""

# revision identifiers, used by Alembic.
revision = '1_starting_point'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_type_created_at'), 'allocation_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_allocation_type_last_updated_at'), 'allocation_type', ['last_updated_at'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_created_at'), 'application', ['created_at'], unique=False)
    op.create_index(op.f('ix_application_last_updated_at'), 'application', ['last_updated_at'], unique=False)
    op.create_table('deployment_target_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_target_type_created_at'), 'deployment_target_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_deployment_target_type_last_updated_at'), 'deployment_target_type', ['last_updated_at'], unique=False)
    op.create_table('environment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_created_at'), 'environment', ['created_at'], unique=False)
    op.create_index(op.f('ix_environment_last_updated_at'), 'environment', ['last_updated_at'], unique=False)
    op.create_table('language',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_created_at'), 'language', ['created_at'], unique=False)
    op.create_index(op.f('ix_language_last_updated_at'), 'language', ['last_updated_at'], unique=False)
    op.create_table('provider_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_type_created_at'), 'provider_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_provider_type_last_updated_at'), 'provider_type', ['last_updated_at'], unique=False)
    op.create_table('repo_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_type_created_at'), 'repo_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_repo_type_last_updated_at'), 'repo_type', ['last_updated_at'], unique=False)
    op.create_table('config_template',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('doc', sa.Text(), nullable=False),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_template_created_at'), 'config_template', ['created_at'], unique=False)
    op.create_index(op.f('ix_config_template_language_id'), 'config_template', ['language_id'], unique=False)
    op.create_index(op.f('ix_config_template_last_updated_at'), 'config_template', ['last_updated_at'], unique=False)
    op.create_table('fleet_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['provider_type_id'], ['provider_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_type_created_at'), 'fleet_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_fleet_type_last_updated_at'), 'fleet_type', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_fleet_type_name'), 'fleet_type', ['name'], unique=False)
    op.create_index(op.f('ix_fleet_type_provider_type_id'), 'fleet_type', ['provider_type_id'], unique=False)
    op.create_table('provider',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_type_id', sa.String(), nullable=False),
    sa.Column('environment_id', sa.String(), nullable=False),
    sa.Column('native_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['provider_type_id'], ['provider_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_created_at'), 'provider', ['created_at'], unique=False)
    op.create_index(op.f('ix_provider_environment_id'), 'provider', ['environment_id'], unique=False)
    op.create_index(op.f('ix_provider_last_updated_at'), 'provider', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_provider_native_id'), 'provider', ['native_id'], unique=False)
    op.create_index(op.f('ix_provider_provider_type_id'), 'provider', ['provider_type_id'], unique=False)
    op.create_table('repo',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repo_type_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=253), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['repo_type_id'], ['repo_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_created_at'), 'repo', ['created_at'], unique=False)
    op.create_index(op.f('ix_repo_last_updated_at'), 'repo', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_repo_repo_type_id'), 'repo', ['repo_type_id'], unique=False)
    op.create_table('stack',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stack_application_id'), 'stack', ['application_id'], unique=False)
    op.create_index(op.f('ix_stack_created_at'), 'stack', ['created_at'], unique=False)
    op.create_index(op.f('ix_stack_last_updated_at'), 'stack', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_stack_name'), 'stack', ['name'], unique=False)
    op.create_table('region',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.Column('native_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_created_at'), 'region', ['created_at'], unique=False)
    op.create_index(op.f('ix_region_last_updated_at'), 'region', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_region_name'), 'region', ['name'], unique=False)
    op.create_index(op.f('ix_region_native_id'), 'region', ['native_id'], unique=False)
    op.create_index(op.f('ix_region_provider_id'), 'region', ['provider_id'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stack_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artifact_name', sa.String(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_artifact_name'), 'service', ['artifact_name'], unique=False)
    op.create_index(op.f('ix_service_created_at'), 'service', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_last_updated_at'), 'service', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_service_name'), 'service', ['name'], unique=False)
    op.create_index(op.f('ix_service_stack_id'), 'service', ['stack_id'], unique=False)
    op.create_table('stack_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_template_id', sa.String(), nullable=True),
    sa.Column('stack_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_template_id'], ['config_template.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('build',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('build_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('ver', sa.String(), nullable=False),
    sa.Column('vcs_ref', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_created_at'), 'build', ['created_at'], unique=False)
    op.create_index(op.f('ix_build_last_updated_at'), 'build', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_build_service_id'), 'build', ['service_id'], unique=False)
    op.create_table('partition',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('native_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partition_created_at'), 'partition', ['created_at'], unique=False)
    op.create_index(op.f('ix_partition_last_updated_at'), 'partition', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_partition_name'), 'partition', ['name'], unique=False)
    op.create_index(op.f('ix_partition_native_id'), 'partition', ['native_id'], unique=False)
    op.create_index(op.f('ix_partition_region_id'), 'partition', ['region_id'], unique=False)
    op.create_table('proc',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proc_created_at'), 'proc', ['created_at'], unique=False)
    op.create_index(op.f('ix_proc_last_updated_at'), 'proc', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_proc_name'), 'proc', ['name'], unique=False)
    op.create_index(op.f('ix_proc_service_id'), 'proc', ['service_id'], unique=False)
    op.create_table('service_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_template_id', sa.String(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_template_id'], ['config_template.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_repos',
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('repo_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], )
    )
    op.create_table('zone',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('native_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_created_at'), 'zone', ['created_at'], unique=False)
    op.create_index(op.f('ix_zone_last_updated_at'), 'zone', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_zone_name'), 'zone', ['name'], unique=False)
    op.create_index(op.f('ix_zone_native_id'), 'zone', ['native_id'], unique=False)
    op.create_index(op.f('ix_zone_region_id'), 'zone', ['region_id'], unique=False)
    op.create_table('build_artifact',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('build_id', sa.String(), nullable=False),
    sa.Column('input_repo_id', sa.String(), nullable=False),
    sa.Column('output_repo_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('upload_path', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['build.id'], ),
    sa.ForeignKeyConstraint(['input_repo_id'], ['repo.id'], ),
    sa.ForeignKeyConstraint(['output_repo_id'], ['repo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_artifact_build_id'), 'build_artifact', ['build_id'], unique=False)
    op.create_index(op.f('ix_build_artifact_created_at'), 'build_artifact', ['created_at'], unique=False)
    op.create_index(op.f('ix_build_artifact_input_repo_id'), 'build_artifact', ['input_repo_id'], unique=False)
    op.create_index(op.f('ix_build_artifact_last_updated_at'), 'build_artifact', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_build_artifact_output_repo_id'), 'build_artifact', ['output_repo_id'], unique=False)
    op.create_table('deployment_target',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deployment_target_type_id', sa.String(), nullable=True),
    sa.Column('partition_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.Column('native_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_target_type_id'], ['deployment_target_type.id'], ),
    sa.ForeignKeyConstraint(['partition_id'], ['partition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_target_created_at'), 'deployment_target', ['created_at'], unique=False)
    op.create_index(op.f('ix_deployment_target_deployment_target_type_id'), 'deployment_target', ['deployment_target_type_id'], unique=False)
    op.create_index(op.f('ix_deployment_target_last_updated_at'), 'deployment_target', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_deployment_target_name'), 'deployment_target', ['name'], unique=False)
    op.create_index(op.f('ix_deployment_target_partition_id'), 'deployment_target', ['partition_id'], unique=False)
    op.create_table('network',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('partition_id', sa.String(), nullable=False),
    sa.Column('native_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cidr', postgresql.CIDR(), nullable=False),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['partition_id'], ['partition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_cidr'), 'network', ['cidr'], unique=False)
    op.create_index(op.f('ix_network_created_at'), 'network', ['created_at'], unique=False)
    op.create_index(op.f('ix_network_last_updated_at'), 'network', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_network_name'), 'network', ['name'], unique=False)
    op.create_index(op.f('ix_network_native_id'), 'network', ['native_id'], unique=False)
    op.create_index(op.f('ix_network_partition_id'), 'network', ['partition_id'], unique=False)
    op.create_table('deployment_target_bin',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), server_default='default', nullable=False),
    sa.Column('deployment_target_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_target_id'], ['deployment_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_target_bin_created_at'), 'deployment_target_bin', ['created_at'], unique=False)
    op.create_index(op.f('ix_deployment_target_bin_deployment_target_id'), 'deployment_target_bin', ['deployment_target_id'], unique=False)
    op.create_index(op.f('ix_deployment_target_bin_last_updated_at'), 'deployment_target_bin', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_deployment_target_bin_name'), 'deployment_target_bin', ['name'], unique=False)
    op.create_table('fleet',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deployment_target_id', sa.String(), nullable=True),
    sa.Column('fleet_type_id', sa.String(), nullable=True),
    sa.Column('native_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_target_id'], ['deployment_target.id'], ),
    sa.ForeignKeyConstraint(['fleet_type_id'], ['fleet_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_created_at'), 'fleet', ['created_at'], unique=False)
    op.create_index(op.f('ix_fleet_deployment_target_id'), 'fleet', ['deployment_target_id'], unique=False)
    op.create_index(op.f('ix_fleet_fleet_type_id'), 'fleet', ['fleet_type_id'], unique=False)
    op.create_index(op.f('ix_fleet_last_updated_at'), 'fleet', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_fleet_name'), 'fleet', ['name'], unique=False)
    op.create_index(op.f('ix_fleet_native_id'), 'fleet', ['native_id'], unique=False)
    op.create_table('subnet',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('network_id', sa.String(), nullable=False),
    sa.Column('native_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cidr', postgresql.CIDR(), nullable=False),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subnet_cidr'), 'subnet', ['cidr'], unique=False)
    op.create_index(op.f('ix_subnet_created_at'), 'subnet', ['created_at'], unique=False)
    op.create_index(op.f('ix_subnet_last_updated_at'), 'subnet', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_subnet_name'), 'subnet', ['name'], unique=False)
    op.create_index(op.f('ix_subnet_native_id'), 'subnet', ['native_id'], unique=False)
    op.create_index(op.f('ix_subnet_network_id'), 'subnet', ['network_id'], unique=False)
    op.create_table('capacity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fleet_id', sa.String(), nullable=True),
    sa.Column('allocation_type_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_type_id'], ['allocation_type.id'], ),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capacity_allocation_type_id'), 'capacity', ['allocation_type_id'], unique=False)
    op.create_index(op.f('ix_capacity_created_at'), 'capacity', ['created_at'], unique=False)
    op.create_index(op.f('ix_capacity_fleet_id'), 'capacity', ['fleet_id'], unique=False)
    op.create_index(op.f('ix_capacity_last_updated_at'), 'capacity', ['last_updated_at'], unique=False)
    op.create_table('deployment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deployment_target_bin_id', sa.String(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('current_release_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['current_release_id'], ['release.id'], name='deployment_current_release_id_fkey', use_alter=True),
    sa.ForeignKeyConstraint(['deployment_target_bin_id'], ['deployment_target_bin.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_created_at'), 'deployment', ['created_at'], unique=False)
    op.create_index(op.f('ix_deployment_current_release_id'), 'deployment', ['current_release_id'], unique=False)
    op.create_index(op.f('ix_deployment_deployment_target_bin_id'), 'deployment', ['deployment_target_bin_id'], unique=False)
    op.create_index(op.f('ix_deployment_last_updated_at'), 'deployment', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_deployment_service_id'), 'deployment', ['service_id'], unique=False)
    op.create_index(op.f('ix_deployment_tag'), 'deployment', ['tag'], unique=False)
    op.create_table('subnets_fleets',
    sa.Column('subnet_id', sa.String(), nullable=True),
    sa.Column('fleet_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleet.id'], ),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnet.id'], )
    )
    op.create_index('ix_subnets_to_fleets_fleet_id', 'subnets_fleets', ['fleet_id'], unique=False)
    op.create_index('ix_subnets_to_fleets_subnet_id', 'subnets_fleets', ['subnet_id'], unique=False)
    op.create_table('target_bins_fleets',
    sa.Column('deployment_target_bin_id', sa.String(), nullable=True),
    sa.Column('fleet_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_target_bin_id'], ['deployment_target_bin.id'], ),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleet.id'], )
    )
    op.create_index('ix_target_bins_to_fleets_deployment_target_bin_id', 'target_bins_fleets', ['deployment_target_bin_id'], unique=False)
    op.create_index('ix_target_bins_to_fleets_fleet_id', 'target_bins_fleets', ['fleet_id'], unique=False)
    op.create_table('deployment_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_template_id', sa.String(), nullable=True),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_template_id'], ['config_template.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_config_config_template_id'), 'deployment_config', ['config_template_id'], unique=False)
    op.create_index(op.f('ix_deployment_config_created_at'), 'deployment_config', ['created_at'], unique=False)
    op.create_index(op.f('ix_deployment_config_deployment_id'), 'deployment_config', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_config_last_updated_at'), 'deployment_config', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_deployment_config_name'), 'deployment_config', ['name'], unique=False)
    op.create_index(op.f('ix_deployment_config_tag'), 'deployment_config', ['tag'], unique=False)
    op.create_table('deployment_proc',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.Column('proc_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['proc_id'], ['proc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_proc_created_at'), 'deployment_proc', ['created_at'], unique=False)
    op.create_index(op.f('ix_deployment_proc_deployment_id'), 'deployment_proc', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_proc_last_updated_at'), 'deployment_proc', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_deployment_proc_proc_id'), 'deployment_proc', ['proc_id'], unique=False)
    op.create_table('deployments_zones',
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], )
    )
    op.create_index('ix_deps_to_zones_deployment_id', 'deployments_zones', ['deployment_id'], unique=False)
    op.create_index('ix_deps_to_zones_zone_id', 'deployments_zones', ['zone_id'], unique=False)
    op.create_table('release',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('build_id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('build_num', sa.Integer(), nullable=False),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['build.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_build_id'), 'release', ['build_id'], unique=False)
    op.create_index(op.f('ix_release_build_num'), 'release', ['build_num'], unique=False)
    op.create_index(op.f('ix_release_created_at'), 'release', ['created_at'], unique=False)
    op.create_index(op.f('ix_release_deployment_id'), 'release', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_release_last_updated_at'), 'release', ['last_updated_at'], unique=False)
    op.create_table('allocation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('allocation_type_id', sa.String(), nullable=True),
    sa.Column('deployment_proc_id', sa.String(), nullable=True),
    sa.Column('watermark', sa.Enum('HIGH', 'LOW', name='watermark'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_type_id'], ['allocation_type.id'], ),
    sa.ForeignKeyConstraint(['deployment_proc_id'], ['deployment_proc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_allocation_type_id'), 'allocation', ['allocation_type_id'], unique=False)
    op.create_index(op.f('ix_allocation_created_at'), 'allocation', ['created_at'], unique=False)
    op.create_index(op.f('ix_allocation_deployment_proc_id'), 'allocation', ['deployment_proc_id'], unique=False)
    op.create_index(op.f('ix_allocation_last_updated_at'), 'allocation', ['last_updated_at'], unique=False)
    op.create_table('release_artifact',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('release_id', sa.String(), nullable=False),
    sa.Column('input_repo_id', sa.String(), nullable=False),
    sa.Column('output_repo_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('upload_path', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['input_repo_id'], ['repo.id'], ),
    sa.ForeignKeyConstraint(['output_repo_id'], ['repo.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_artifact')
    op.drop_index(op.f('ix_allocation_last_updated_at'), table_name='allocation')
    op.drop_index(op.f('ix_allocation_deployment_proc_id'), table_name='allocation')
    op.drop_index(op.f('ix_allocation_created_at'), table_name='allocation')
    op.drop_index(op.f('ix_allocation_allocation_type_id'), table_name='allocation')
    op.drop_table('allocation')
    op.drop_index(op.f('ix_release_last_updated_at'), table_name='release')
    op.drop_index(op.f('ix_release_deployment_id'), table_name='release')
    op.drop_index(op.f('ix_release_created_at'), table_name='release')
    op.drop_index(op.f('ix_release_build_num'), table_name='release')
    op.drop_index(op.f('ix_release_build_id'), table_name='release')
    op.drop_table('release')
    op.drop_index('ix_deps_to_zones_zone_id', table_name='deployments_zones')
    op.drop_index('ix_deps_to_zones_deployment_id', table_name='deployments_zones')
    op.drop_table('deployments_zones')
    op.drop_index(op.f('ix_deployment_proc_proc_id'), table_name='deployment_proc')
    op.drop_index(op.f('ix_deployment_proc_last_updated_at'), table_name='deployment_proc')
    op.drop_index(op.f('ix_deployment_proc_deployment_id'), table_name='deployment_proc')
    op.drop_index(op.f('ix_deployment_proc_created_at'), table_name='deployment_proc')
    op.drop_table('deployment_proc')
    op.drop_index(op.f('ix_deployment_config_tag'), table_name='deployment_config')
    op.drop_index(op.f('ix_deployment_config_name'), table_name='deployment_config')
    op.drop_index(op.f('ix_deployment_config_last_updated_at'), table_name='deployment_config')
    op.drop_index(op.f('ix_deployment_config_deployment_id'), table_name='deployment_config')
    op.drop_index(op.f('ix_deployment_config_created_at'), table_name='deployment_config')
    op.drop_index(op.f('ix_deployment_config_config_template_id'), table_name='deployment_config')
    op.drop_table('deployment_config')
    op.drop_index('ix_target_bins_to_fleets_fleet_id', table_name='target_bins_fleets')
    op.drop_index('ix_target_bins_to_fleets_deployment_target_bin_id', table_name='target_bins_fleets')
    op.drop_table('target_bins_fleets')
    op.drop_index('ix_subnets_to_fleets_subnet_id', table_name='subnets_fleets')
    op.drop_index('ix_subnets_to_fleets_fleet_id', table_name='subnets_fleets')
    op.drop_table('subnets_fleets')
    op.drop_index(op.f('ix_deployment_tag'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_service_id'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_last_updated_at'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_deployment_target_bin_id'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_current_release_id'), table_name='deployment')
    op.drop_index(op.f('ix_deployment_created_at'), table_name='deployment')
    op.drop_table('deployment')
    op.drop_index(op.f('ix_capacity_last_updated_at'), table_name='capacity')
    op.drop_index(op.f('ix_capacity_fleet_id'), table_name='capacity')
    op.drop_index(op.f('ix_capacity_created_at'), table_name='capacity')
    op.drop_index(op.f('ix_capacity_allocation_type_id'), table_name='capacity')
    op.drop_table('capacity')
    op.drop_index(op.f('ix_subnet_network_id'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_native_id'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_name'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_last_updated_at'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_created_at'), table_name='subnet')
    op.drop_index(op.f('ix_subnet_cidr'), table_name='subnet')
    op.drop_table('subnet')
    op.drop_index(op.f('ix_fleet_native_id'), table_name='fleet')
    op.drop_index(op.f('ix_fleet_name'), table_name='fleet')
    op.drop_index(op.f('ix_fleet_last_updated_at'), table_name='fleet')
    op.drop_index(op.f('ix_fleet_fleet_type_id'), table_name='fleet')
    op.drop_index(op.f('ix_fleet_deployment_target_id'), table_name='fleet')
    op.drop_index(op.f('ix_fleet_created_at'), table_name='fleet')
    op.drop_table('fleet')
    op.drop_index(op.f('ix_deployment_target_bin_name'), table_name='deployment_target_bin')
    op.drop_index(op.f('ix_deployment_target_bin_last_updated_at'), table_name='deployment_target_bin')
    op.drop_index(op.f('ix_deployment_target_bin_deployment_target_id'), table_name='deployment_target_bin')
    op.drop_index(op.f('ix_deployment_target_bin_created_at'), table_name='deployment_target_bin')
    op.drop_table('deployment_target_bin')
    op.drop_index(op.f('ix_network_partition_id'), table_name='network')
    op.drop_index(op.f('ix_network_native_id'), table_name='network')
    op.drop_index(op.f('ix_network_name'), table_name='network')
    op.drop_index(op.f('ix_network_last_updated_at'), table_name='network')
    op.drop_index(op.f('ix_network_created_at'), table_name='network')
    op.drop_index(op.f('ix_network_cidr'), table_name='network')
    op.drop_table('network')
    op.drop_index(op.f('ix_deployment_target_partition_id'), table_name='deployment_target')
    op.drop_index(op.f('ix_deployment_target_name'), table_name='deployment_target')
    op.drop_index(op.f('ix_deployment_target_last_updated_at'), table_name='deployment_target')
    op.drop_index(op.f('ix_deployment_target_deployment_target_type_id'), table_name='deployment_target')
    op.drop_index(op.f('ix_deployment_target_created_at'), table_name='deployment_target')
    op.drop_table('deployment_target')
    op.drop_index(op.f('ix_build_artifact_output_repo_id'), table_name='build_artifact')
    op.drop_index(op.f('ix_build_artifact_last_updated_at'), table_name='build_artifact')
    op.drop_index(op.f('ix_build_artifact_input_repo_id'), table_name='build_artifact')
    op.drop_index(op.f('ix_build_artifact_created_at'), table_name='build_artifact')
    op.drop_index(op.f('ix_build_artifact_build_id'), table_name='build_artifact')
    op.drop_table('build_artifact')
    op.drop_index(op.f('ix_zone_region_id'), table_name='zone')
    op.drop_index(op.f('ix_zone_native_id'), table_name='zone')
    op.drop_index(op.f('ix_zone_name'), table_name='zone')
    op.drop_index(op.f('ix_zone_last_updated_at'), table_name='zone')
    op.drop_index(op.f('ix_zone_created_at'), table_name='zone')
    op.drop_table('zone')
    op.drop_table('services_repos')
    op.drop_table('service_config')
    op.drop_index(op.f('ix_proc_service_id'), table_name='proc')
    op.drop_index(op.f('ix_proc_name'), table_name='proc')
    op.drop_index(op.f('ix_proc_last_updated_at'), table_name='proc')
    op.drop_index(op.f('ix_proc_created_at'), table_name='proc')
    op.drop_table('proc')
    op.drop_index(op.f('ix_partition_region_id'), table_name='partition')
    op.drop_index(op.f('ix_partition_native_id'), table_name='partition')
    op.drop_index(op.f('ix_partition_name'), table_name='partition')
    op.drop_index(op.f('ix_partition_last_updated_at'), table_name='partition')
    op.drop_index(op.f('ix_partition_created_at'), table_name='partition')
    op.drop_table('partition')
    op.drop_index(op.f('ix_build_service_id'), table_name='build')
    op.drop_index(op.f('ix_build_last_updated_at'), table_name='build')
    op.drop_index(op.f('ix_build_created_at'), table_name='build')
    op.drop_table('build')
    op.drop_table('stack_config')
    op.drop_index(op.f('ix_service_stack_id'), table_name='service')
    op.drop_index(op.f('ix_service_name'), table_name='service')
    op.drop_index(op.f('ix_service_last_updated_at'), table_name='service')
    op.drop_index(op.f('ix_service_created_at'), table_name='service')
    op.drop_index(op.f('ix_service_artifact_name'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_region_provider_id'), table_name='region')
    op.drop_index(op.f('ix_region_native_id'), table_name='region')
    op.drop_index(op.f('ix_region_name'), table_name='region')
    op.drop_index(op.f('ix_region_last_updated_at'), table_name='region')
    op.drop_index(op.f('ix_region_created_at'), table_name='region')
    op.drop_table('region')
    op.drop_index(op.f('ix_stack_name'), table_name='stack')
    op.drop_index(op.f('ix_stack_last_updated_at'), table_name='stack')
    op.drop_index(op.f('ix_stack_created_at'), table_name='stack')
    op.drop_index(op.f('ix_stack_application_id'), table_name='stack')
    op.drop_table('stack')
    op.drop_index(op.f('ix_repo_repo_type_id'), table_name='repo')
    op.drop_index(op.f('ix_repo_last_updated_at'), table_name='repo')
    op.drop_index(op.f('ix_repo_created_at'), table_name='repo')
    op.drop_table('repo')
    op.drop_index(op.f('ix_provider_provider_type_id'), table_name='provider')
    op.drop_index(op.f('ix_provider_native_id'), table_name='provider')
    op.drop_index(op.f('ix_provider_last_updated_at'), table_name='provider')
    op.drop_index(op.f('ix_provider_environment_id'), table_name='provider')
    op.drop_index(op.f('ix_provider_created_at'), table_name='provider')
    op.drop_table('provider')
    op.drop_index(op.f('ix_fleet_type_provider_type_id'), table_name='fleet_type')
    op.drop_index(op.f('ix_fleet_type_name'), table_name='fleet_type')
    op.drop_index(op.f('ix_fleet_type_last_updated_at'), table_name='fleet_type')
    op.drop_index(op.f('ix_fleet_type_created_at'), table_name='fleet_type')
    op.drop_table('fleet_type')
    op.drop_index(op.f('ix_config_template_last_updated_at'), table_name='config_template')
    op.drop_index(op.f('ix_config_template_language_id'), table_name='config_template')
    op.drop_index(op.f('ix_config_template_created_at'), table_name='config_template')
    op.drop_table('config_template')
    op.drop_index(op.f('ix_repo_type_last_updated_at'), table_name='repo_type')
    op.drop_index(op.f('ix_repo_type_created_at'), table_name='repo_type')
    op.drop_table('repo_type')
    op.drop_index(op.f('ix_provider_type_last_updated_at'), table_name='provider_type')
    op.drop_index(op.f('ix_provider_type_created_at'), table_name='provider_type')
    op.drop_table('provider_type')
    op.drop_index(op.f('ix_language_last_updated_at'), table_name='language')
    op.drop_index(op.f('ix_language_created_at'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_environment_last_updated_at'), table_name='environment')
    op.drop_index(op.f('ix_environment_created_at'), table_name='environment')
    op.drop_table('environment')
    op.drop_index(op.f('ix_deployment_target_type_last_updated_at'), table_name='deployment_target_type')
    op.drop_index(op.f('ix_deployment_target_type_created_at'), table_name='deployment_target_type')
    op.drop_table('deployment_target_type')
    op.drop_index(op.f('ix_application_last_updated_at'), table_name='application')
    op.drop_index(op.f('ix_application_created_at'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_allocation_type_last_updated_at'), table_name='allocation_type')
    op.drop_index(op.f('ix_allocation_type_created_at'), table_name='allocation_type')
    op.drop_table('allocation_type')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass
