"""empty message

Revision ID: use_alters
Revises: starting_point
Create Date: 2023-08-12 10:15:57.136932

"""

# revision identifiers, used by Alembic.
revision = '2_use_alters'
down_revision = '1_starting_point'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('deployment_current_release_id_fkey', 'deployment', 'release', ['current_release_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deployment_current_release_id_fkey', 'deployment', type_='foreignkey')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass
