"""empty message

Revision ID: 3729e673db6a
Revises: 2b28d97ccb94
Create Date: 2021-06-07 16:07:41.339275

"""

# revision identifiers, used by Alembic.
revision = '3729e673db6a'
down_revision = '2b28d97ccb94'

from alembic import op
import sqlalchemy as sa

from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deployment_target', 'native',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    new_column_name='native_id',
                    existing_nullable=True)
    op.alter_column('fleet', 'native',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    new_column_name='native_id',
                    existing_nullable=True)
    op.alter_column('network', 'native',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    new_column_name='native_id',
                    existing_nullable=True)
    op.alter_column('partition', 'native',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    new_column_name='native_id',
                    existing_nullable=True)
    op.alter_column('provider', 'native',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    new_column_name='native_id',
                    existing_nullable=True)
    op.alter_column('region', 'native',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    new_column_name='native_id',
                    existing_nullable=True)
    op.alter_column('subnet', 'native',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    new_column_name='native_id',
                    existing_nullable=True)
    op.alter_column('zone', 'native',
                    existing_type=sa.TEXT(),
                    type_=sa.String(),
                    new_column_name='native_id',
                    existing_nullable=True)
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zone', 'native_id',
                    new_column_name='native',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),

                    existing_nullable=True)
    op.alter_column('subnet', 'native_id',
                    new_column_name='native', existing_type=sa.String(),
                    type_=sa.TEXT(),

                    existing_nullable=True)
    op.alter_column('region', 'native_id',
                    new_column_name='native',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),

                    existing_nullable=True)
    op.alter_column('provider', 'native_id',
                    new_column_name='native',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),

                    existing_nullable=True)
    op.alter_column('partition', 'native_id',
                    new_column_name='native',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),

                    existing_nullable=True)
    op.alter_column('network', 'native_id',
                    new_column_name='native',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),

                    existing_nullable=True)
    op.alter_column('fleet', 'native_id',
                    new_column_name='native',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),

                    existing_nullable=True)
    op.alter_column('deployment_target', 'native_id',
                    new_column_name='native',
                    existing_type=sa.String(),
                    type_=sa.TEXT(),

                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass
