"""empty message

Revision ID: 3_dependencies_plugin
Revises: 2_use_alters
Create Date: 2023-08-15 12:18:34.737372

"""

# revision identifiers, used by Alembic.
revision = '3_dependencies_plugin'
down_revision = '2_use_alters'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_case',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('relatable_type', sa.String(), nullable=False),
    sa.Column('related_type', sa.String(), nullable=False),
    sa.Column('allowed_relationship', sa.Enum('OTO', 'OTM', name='relationship_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_case_created_at'), 'dependency_case', ['created_at'], unique=False)
    op.create_index(op.f('ix_dependency_case_last_updated_at'), 'dependency_case', ['last_updated_at'], unique=False)
    op.create_table('relatable',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relatable_created_at'), 'relatable', ['created_at'], unique=False)
    op.create_index(op.f('ix_relatable_last_updated_at'), 'relatable', ['last_updated_at'], unique=False)
    op.create_table('related',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_created_at'), 'related', ['created_at'], unique=False)
    op.create_index(op.f('ix_related_last_updated_at'), 'related', ['last_updated_at'], unique=False)
    op.create_table('dependency',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dependency_case_id', sa.String(), nullable=True),
    sa.Column('relatable_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_case_id'], ['dependency_case.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['relatable_id'], ['relatable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_created_at'), 'dependency', ['created_at'], unique=False)
    op.create_index(op.f('ix_dependency_last_updated_at'), 'dependency', ['last_updated_at'], unique=False)
    op.create_table('dependency_relateds',
    sa.Column('dependency_id', sa.String(), nullable=True),
    sa.Column('related_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependency.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['related_id'], ['related.id'], onupdate='CASCADE')
    )
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependency_relateds')
    op.drop_index(op.f('ix_dependency_last_updated_at'), table_name='dependency')
    op.drop_index(op.f('ix_dependency_created_at'), table_name='dependency')
    op.drop_table('dependency')
    op.drop_index(op.f('ix_related_last_updated_at'), table_name='related')
    op.drop_index(op.f('ix_related_created_at'), table_name='related')
    op.drop_table('related')
    op.drop_index(op.f('ix_relatable_last_updated_at'), table_name='relatable')
    op.drop_index(op.f('ix_relatable_created_at'), table_name='relatable')
    op.drop_table('relatable')
    op.drop_index(op.f('ix_dependency_case_last_updated_at'), table_name='dependency_case')
    op.drop_index(op.f('ix_dependency_case_created_at'), table_name='dependency_case')
    op.drop_table('dependency_case')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass