"""empty message

Revision ID: 3_dependencies_plugin
Revises: 2_use_alters
Create Date: 2023-08-15 16:15:24.596544

"""

# revision identifiers, used by Alembic.
revision = '3_dependencies_plugin'
down_revision = '2_use_alters'

import sqlalchemy as sa
from alembic import op


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_dependencies_dependency_case',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('relatable_type', sa.String(), nullable=False),
                    sa.Column('related_type', sa.String(), nullable=False),
                    sa.Column('allowed_relationship', sa.Enum('OTO', 'OTM', name='relationship_type'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_dependency_case_created_at'), 'plugin_dependencies_dependency_case', ['created_at'],
                    unique=False)
    op.create_index(op.f('ix_dependency_case_last_updated_at'), 'plugin_dependencies_dependency_case',
                    ['last_updated_at'], unique=False)
    op.create_table('plugin_dependencies_relatable',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('object_id', sa.String(), nullable=False),
                    sa.Column('relatable_type', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_relatable_created_at'), 'plugin_dependencies_relatable', ['created_at'], unique=False)
    op.create_index(op.f('ix_relatable_last_updated_at'), 'plugin_dependencies_relatable', ['last_updated_at'],
                    unique=False)
    op.create_table('plugin_dependencies_dependency',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('dependency_case_id', sa.String(), nullable=True),
                    sa.Column('relatable_id', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(tuple(['dependency_case_id']),
                                            ['plugin_dependencies_dependency_case.id'], ),
                    sa.ForeignKeyConstraint(tuple(['relatable_id']), ['plugin_dependencies_relatable.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('dependency_case_id', 'relatable_id', name='UniqueDependency')
                    )
    op.create_index(op.f('ix_dependency_created_at'), 'plugin_dependencies_dependency', ['created_at'], unique=False)
    op.create_index(op.f('ix_dependency_last_updated_at'), 'plugin_dependencies_dependency', ['last_updated_at'],
                    unique=False)
    op.create_table('plugin_dependencies_related',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('dependency_id', sa.String(), nullable=False),
                    sa.Column('object_id', sa.String(), nullable=True),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(tuple(['dependency_id']), ['plugin_dependencies_dependency.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_related_created_at'), 'plugin_dependencies_related', ['created_at'], unique=False)
    op.create_index(op.f('ix_related_last_updated_at'), 'plugin_dependencies_related', ['last_updated_at'],
                    unique=False)
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_related_last_updated_at'), table_name='plugin_dependencies_related')
    op.drop_index(op.f('ix_related_created_at'), table_name='plugin_dependencies_related')
    op.drop_table('plugin_dependencies_related')
    op.drop_index(op.f('ix_dependency_last_updated_at'), table_name='plugin_dependencies_dependency')
    op.drop_index(op.f('ix_dependency_created_at'), table_name='plugin_dependencies_dependency')
    op.drop_table('plugin_dependencies_dependency')
    op.drop_index(op.f('ix_relatable_last_updated_at'), table_name='plugin_dependencies_relatable')
    op.drop_index(op.f('ix_relatable_created_at'), table_name='plugin_dependencies_relatable')
    op.drop_table('plugin_dependencies_relatable')
    op.drop_index(op.f('ix_dependency_case_last_updated_at'), table_name='plugin_dependencies_dependency_case')
    op.drop_index(op.f('ix_dependency_case_created_at'), table_name='plugin_dependencies_dependency_case')
    op.drop_table('plugin_dependencies_dependency_case')
    op.execute('drop type public.relationship_type;')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass
