"""empty message

Revision ID: 458fa8fdfd1e
Revises: 29cf6623ae3e
Create Date: 2021-08-05 22:21:00.876401

"""

# revision identifiers, used by Alembic.
revision = '458fa8fdfd1e'
down_revision = '29cf6623ae3e'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'deployment', 'release', ['current_release_id'], ['id'])
    # ### end Alembic commands ###


def upgrades_post():
    query = """update deployment d set current_release_id=sel.release_id from (select cdr.* from current_dep_release cdr, deployment d, release r where cdr.deployment_id=d.id and cdr.release_id=r.id) as sel where d.id=sel.deployment_id;"""
    op.execute(query)
    # removing unused f



def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployment', type_='foreignkey')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass
