"""empty message

Revision ID: 00494f6ed089
Revises: 3_dependencies_plugin
Create Date: 2025-05-16 16:26:41.792339

"""

# revision identifiers, used by Alembic.
revision = '4_create_dependency_plugin_tables'
down_revision = '3_dependencies_plugin'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('tenant_id', sa.String(), nullable=False))
    op.drop_index('ix_dependency_created_at', table_name='plugin_dependencies_dependency')
    op.drop_index('ix_dependency_last_updated_at', table_name='plugin_dependencies_dependency')
    op.create_index(op.f('ix_plugin_dependencies_dependency_created_at'), 'plugin_dependencies_dependency', ['created_at'], unique=False)
    op.create_index(op.f('ix_plugin_dependencies_dependency_last_updated_at'), 'plugin_dependencies_dependency', ['last_updated_at'], unique=False)
    op.drop_index('ix_dependency_case_created_at', table_name='plugin_dependencies_dependency_case')
    op.drop_index('ix_dependency_case_last_updated_at', table_name='plugin_dependencies_dependency_case')
    op.create_index(op.f('ix_plugin_dependencies_dependency_case_created_at'), 'plugin_dependencies_dependency_case', ['created_at'], unique=False)
    op.create_index(op.f('ix_plugin_dependencies_dependency_case_last_updated_at'), 'plugin_dependencies_dependency_case', ['last_updated_at'], unique=False)
    op.drop_index('ix_relatable_created_at', table_name='plugin_dependencies_relatable')
    op.drop_index('ix_relatable_last_updated_at', table_name='plugin_dependencies_relatable')
    op.create_index(op.f('ix_plugin_dependencies_relatable_created_at'), 'plugin_dependencies_relatable', ['created_at'], unique=False)
    op.create_index(op.f('ix_plugin_dependencies_relatable_last_updated_at'), 'plugin_dependencies_relatable', ['last_updated_at'], unique=False)
    op.alter_column('plugin_dependencies_related', 'object_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('plugin_dependencies_related', 'related_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_related_created_at', table_name='plugin_dependencies_related')
    op.drop_index('ix_related_last_updated_at', table_name='plugin_dependencies_related')
    op.create_index(op.f('ix_plugin_dependencies_related_created_at'), 'plugin_dependencies_related', ['created_at'], unique=False)
    op.create_index(op.f('ix_plugin_dependencies_related_last_updated_at'), 'plugin_dependencies_related', ['last_updated_at'], unique=False)
    op.add_column('proc', sa.Column('tenant_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_proc_tenant_id'), 'proc', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proc_tenant_id'), table_name='proc')
    op.drop_column('proc', 'tenant_id')
    op.drop_index(op.f('ix_plugin_dependencies_related_last_updated_at'), table_name='plugin_dependencies_related')
    op.drop_index(op.f('ix_plugin_dependencies_related_created_at'), table_name='plugin_dependencies_related')
    op.create_index('ix_related_last_updated_at', 'plugin_dependencies_related', ['last_updated_at'], unique=False)
    op.create_index('ix_related_created_at', 'plugin_dependencies_related', ['created_at'], unique=False)
    op.alter_column('plugin_dependencies_related', 'related_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('plugin_dependencies_related', 'object_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_plugin_dependencies_relatable_last_updated_at'), table_name='plugin_dependencies_relatable')
    op.drop_index(op.f('ix_plugin_dependencies_relatable_created_at'), table_name='plugin_dependencies_relatable')
    op.create_index('ix_relatable_last_updated_at', 'plugin_dependencies_relatable', ['last_updated_at'], unique=False)
    op.create_index('ix_relatable_created_at', 'plugin_dependencies_relatable', ['created_at'], unique=False)
    op.drop_index(op.f('ix_plugin_dependencies_dependency_case_last_updated_at'), table_name='plugin_dependencies_dependency_case')
    op.drop_index(op.f('ix_plugin_dependencies_dependency_case_created_at'), table_name='plugin_dependencies_dependency_case')
    op.create_index('ix_dependency_case_last_updated_at', 'plugin_dependencies_dependency_case', ['last_updated_at'], unique=False)
    op.create_index('ix_dependency_case_created_at', 'plugin_dependencies_dependency_case', ['created_at'], unique=False)
    op.drop_index(op.f('ix_plugin_dependencies_dependency_last_updated_at'), table_name='plugin_dependencies_dependency')
    op.drop_index(op.f('ix_plugin_dependencies_dependency_created_at'), table_name='plugin_dependencies_dependency')
    op.create_index('ix_dependency_last_updated_at', 'plugin_dependencies_dependency', ['last_updated_at'], unique=False)
    op.create_index('ix_dependency_created_at', 'plugin_dependencies_dependency', ['created_at'], unique=False)
    op.drop_column('application', 'tenant_id')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass