"""empty message

Revision ID: 58b14ce55967
Revises: add_stack_config
Create Date: 2023-08-09 11:52:42.745176

"""

# revision identifiers, used by Alembic.
revision = '58b14ce55967'
down_revision = 'add_stack_config'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_case',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('allowed_related_type', sa.String(), nullable=True),
    sa.Column('allowed_relationship', sa.Enum('OTO', 'OTM', name='relationship_type'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatable',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('relatable_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('related_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dependency_case_id', sa.String(), nullable=True),
    sa.Column('relatable_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_case_id'], ['dependency_case.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['relatable_id'], ['relatable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency_relateds',
    sa.Column('dependency_id', sa.String(), nullable=True),
    sa.Column('related_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependency.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['related_id'], ['related.id'], onupdate='CASCADE')
    )
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependency_relateds')
    op.drop_table('dependency')
    op.drop_table('child')
    op.drop_table('related')
    op.drop_table('relatable')
    op.drop_table('parent')
    op.drop_table('dependency_case')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass