"""empty message

Revision ID: 40ca22c9fb9f
Revises: 00494f6ed089
Create Date: 2025-05-16 16:28:58.773652

"""

# revision identifiers, used by Alembic.
revision = '5_add_tenant_id'
down_revision = '4_create_dependency_plugin_tables'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocation', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('allocation_type', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('build', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('build_artifact', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('capacity', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('config_template', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('deployment', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('deployment_config', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('deployment_proc', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('deployment_target', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('deployment_target_bin', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('deployment_target_type', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('environment', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('fleet', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('fleet_type', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('language', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('network', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('partition', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('provider', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('provider_type', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('region', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('release', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('release_artifact', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('repo', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('repo_type', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('service', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('service_config', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('stack', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('stack_config', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('subnet', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('zone', sa.Column('tenant_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone', 'tenant_id')
    op.drop_column('subnet', 'tenant_id')
    op.drop_column('stack_config', 'tenant_id')
    op.drop_column('stack', 'tenant_id')
    op.drop_column('service_config', 'tenant_id')
    op.drop_column('service', 'tenant_id')
    op.drop_column('repo_type', 'tenant_id')
    op.drop_column('repo', 'tenant_id')
    op.drop_column('release_artifact', 'tenant_id')
    op.drop_column('release', 'tenant_id')
    op.drop_column('region', 'tenant_id')
    op.drop_column('provider_type', 'tenant_id')
    op.drop_column('provider', 'tenant_id')
    op.drop_column('partition', 'tenant_id')
    op.drop_column('network', 'tenant_id')
    op.drop_column('language', 'tenant_id')
    op.drop_column('fleet_type', 'tenant_id')
    op.drop_column('fleet', 'tenant_id')
    op.drop_column('environment', 'tenant_id')
    op.drop_column('deployment_target_type', 'tenant_id')
    op.drop_column('deployment_target_bin', 'tenant_id')
    op.drop_column('deployment_target', 'tenant_id')
    op.drop_column('deployment_proc', 'tenant_id')
    op.drop_column('deployment_config', 'tenant_id')
    op.drop_column('deployment', 'tenant_id')
    op.drop_column('config_template', 'tenant_id')
    op.drop_column('capacity', 'tenant_id')
    op.drop_column('build_artifact', 'tenant_id')
    op.drop_column('build', 'tenant_id')
    op.drop_column('allocation_type', 'tenant_id')
    op.drop_column('allocation', 'tenant_id')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass