"""empty message

Revision ID: 69c4ff789991
Revises: 4b3c780c5318
Create Date: 2021-10-05 14:02:28.470631

"""

# revision identifiers, used by Alembic.
revision = '69c4ff789991'
down_revision = '4b3c780c5318'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('build', 'git_tag', new_column_name='vcs_ref')
    op.add_column('build', sa.Column('ver', sa.String(), nullable=False, server_default='0.0.0.0'))
    op.alter_column('build',  'ver', server_default=None)
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('build', 'vcs_ref', new_column_name='git_tag')
    op.drop_column('build', 'ver')

    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass