"""empty message

Revision ID: 7db6f5fbdcd6
Revises: add_deployment_target_bin
Create Date: 2022-08-17 13:09:10.770155

"""

# revision identifiers, used by Alembic.
revision = '7db6f5fbdcd6'
down_revision = 'add_deployment_target_bin'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_bins_fleets',
    sa.Column('deployment_target_bin_id', sa.String(), nullable=True),
    sa.Column('fleet_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_target_bin_id'], ['deployment_target_bin.id'], ),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleet.id'], )
    )
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_bins_fleets')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass