"""empty message

Revision ID: 87b807ccb3eb
Revises: a766f3aae357
Create Date: 2022-03-10 13:43:24.398434

"""

# revision identifiers, used by Alembic.
revision = '87b807ccb3eb'
down_revision = 'a766f3aae357'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_config', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('service_config', sa.Column('defaults', sa.Text(), nullable=True))
    op.add_column('service_config', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_config', 'last_updated_at')
    op.drop_column('service_config', 'defaults')
    op.drop_column('service_config', 'created_at')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass