"""empty message

Revision ID: 3030afe5bc81
Revises: target_bins_fleets
Create Date: 2022-11-08 11:37:44.995435

"""

# revision identifiers, used by Alembic.
revision = 'add_stack_config'
down_revision = 'target_bins_fleets'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stack_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_template_id', sa.String(), nullable=True),
    sa.Column('stack_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('defaults', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_template_id'], ['config_template.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_map',
    sa.Column('env_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stack_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bin', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_table('stack_config')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass