"""empty message

Revision ID: f3690b0d5aef
Revises: 58b14ce55967
Create Date: 2023-08-10 20:53:37.695189

"""

# revision identifiers, used by Alembic.
revision = 'f3690b0d5aef'
down_revision = '58b14ce55967'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    upgrades_pre()
    schema_upgrades()
    upgrades_post()


def downgrade():
    downgrades_pre()
    schema_downgrades()
    downgrades_post()


def upgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependency', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('dependency', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_dependency_created_at'), 'dependency', ['created_at'], unique=False)
    op.create_index(op.f('ix_dependency_last_updated_at'), 'dependency', ['last_updated_at'], unique=False)
    op.add_column('dependency_case', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('dependency_case', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_dependency_case_created_at'), 'dependency_case', ['created_at'], unique=False)
    op.create_index(op.f('ix_dependency_case_last_updated_at'), 'dependency_case', ['last_updated_at'], unique=False)
    op.add_column('relatable', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('relatable', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_relatable_created_at'), 'relatable', ['created_at'], unique=False)
    op.create_index(op.f('ix_relatable_last_updated_at'), 'relatable', ['last_updated_at'], unique=False)
    op.add_column('related', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('related', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_related_created_at'), 'related', ['created_at'], unique=False)
    op.create_index(op.f('ix_related_last_updated_at'), 'related', ['last_updated_at'], unique=False)
    # ### end Alembic commands ###


def upgrades_post():
    """Add any optional data prep post migrations here!"""
    pass


def downgrades_pre():
    """Add any optional data prep pre migrations here!"""
    pass


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_related_last_updated_at'), table_name='related')
    op.drop_index(op.f('ix_related_created_at'), table_name='related')
    op.drop_column('related', 'last_updated_at')
    op.drop_column('related', 'created_at')
    op.drop_index(op.f('ix_relatable_last_updated_at'), table_name='relatable')
    op.drop_index(op.f('ix_relatable_created_at'), table_name='relatable')
    op.drop_column('relatable', 'last_updated_at')
    op.drop_column('relatable', 'created_at')
    op.drop_index(op.f('ix_dependency_case_last_updated_at'), table_name='dependency_case')
    op.drop_index(op.f('ix_dependency_case_created_at'), table_name='dependency_case')
    op.drop_column('dependency_case', 'last_updated_at')
    op.drop_column('dependency_case', 'created_at')
    op.drop_index(op.f('ix_dependency_last_updated_at'), table_name='dependency')
    op.drop_index(op.f('ix_dependency_created_at'), table_name='dependency')
    op.drop_column('dependency', 'last_updated_at')
    op.drop_column('dependency', 'created_at')
    # ### end Alembic commands ###


def downgrades_post():
    """Add any optional data prep post migrations here!"""
    pass