image:
  name: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-cicd/microservice-orchestration:1.0.18
  aws:
    access-key: $AWS_EGO_ACCESS_KEY
    secret-key: $AWS_EGO_SECRET_KEY

pipelines:
  tags:
    update-*:
      - step:
          name: Run the production change process
          script:
            - AWS_PROD_ACCESS_KEY=$(/toolbox/get-vault-secret.sh cicd/prod-1/aws_keys AWS_ACCESS_KEY_ID)
            - AWS_PROD_SECRET_KEY=$(/toolbox/get-vault-secret.sh cicd/prod-1/aws_keys AWS_SECRET_ACCESS_KEY)
            - /toolbox/set-aws-credentials.sh --key-id $AWS_PROD_ACCESS_KEY --secret-access-key $AWS_PROD_SECRET_KEY
            - /toolbox/add-aws-profile-credentials.sh --profile-name prod --key-id $AWS_PROD_ACCESS_KEY --secret-access-key $AWS_PROD_SECRET_KEY
            - aws eks --region us-west-2 update-kubeconfig --name prod-1
            - cd $BITBUCKET_CLONE_DIR && /bin/bash ./scripts/main/create-command-from-tag.sh $BITBUCKET_TAG
    create-*:
      - step:
          name: Run the production change process
          script:
            - AWS_PROD_ACCESS_KEY=$(/toolbox/get-vault-secret.sh cicd/prod-1/aws_keys AWS_ACCESS_KEY_ID)
            - AWS_PROD_SECRET_KEY=$(/toolbox/get-vault-secret.sh cicd/prod-1/aws_keys AWS_SECRET_ACCESS_KEY)
            - /toolbox/set-aws-credentials.sh --key-id $AWS_PROD_ACCESS_KEY --secret-access-key $AWS_PROD_SECRET_KEY
            - /toolbox/add-aws-profile-credentials.sh --profile-name prod --key-id $AWS_PROD_ACCESS_KEY --secret-access-key $AWS_PROD_SECRET_KEY
            - aws eks --region us-west-2 update-kubeconfig --name prod-1
            - cd $BITBUCKET_CLONE_DIR && /bin/bash ./scripts/main/create-command-from-tag.sh $BITBUCKET_TAG
