{
 "title": "Vault Dashboard",
 "description": " ",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Token leases with expiration num",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vault_expire_num_leases" }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pending Tokens",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "vault_token_create_count-vault_token_store_count"
    }
   ]
  },
  {
   "title": "Token Lookup",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_token_lookup_count[1m])",
     "legendFormat": "Lookup"
    }
   ]
  },
  {
   "title": "Token",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vault_token_create_count", "legendFormat": "Create" },
    { "expr": "vault_token_store_count", "legendFormat": "Store" }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Audit Log Request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vault_audit_log_request_count[1m]))",
       "legendFormat": "Request "
      },
      {
       "expr": "sum(irate(vault_audit_log_response_count[1m]))",
       "legendFormat": "Response"
      },
      {
       "expr": "sum(irate(vault_core_handle_request_count[1m]))",
       "legendFormat": "Handled"
      }
     ]
    }
   ]
  },
  { "title": "Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Policy Get",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_policy_get_policy_count[1m]))",
     "legendFormat": "GET"
    }
   ]
  },
  { "title": "Backend Storage (DynamoDB)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "DynamoDB List",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(irate(vault_dynamodb_list_count[10m]))",
     "legendFormat": "list"
    }
   ]
  },
  {
   "title": "DynamoDB GET",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_dynamodb_get_count[10m])",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "DynamoDB Delete",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_dynamodb_delete_count[10m])",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "DynamoDB PUT",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(vault_dynamodb_put_count[5m])",
     "legendFormat": "PUT"
    }
   ]
  }
 ]
}