apiVersion: v1
kind: ConfigMap
metadata:
  name: leaderboard-withme
  namespace: default
  labels:
    owned-by-microservice: configuration-manager
    repo: property
data:
  leaderboard_Withme.yaml: |
    leaderboard:
      client_and_server:
        perm:
          201112:
            property:
              chat_config:
                reward_rate_limit_sec: "60"
            progression:
              xp_for_level:
                1:       "0"
                2:      "20"
                3:      "60"
                4:     "100"
                5:     "180"
                6:     "320"
                7:     "520"
                8:     "770"
                9:    "1070"
                10:   "1420"
                11:   "1820"
                12:   "2270"
                13:   "2770"
                14:   "3320"
                15:   "3920"
                16:   "4570"
                17:   "5270"
                18:   "6020"
                19:   "6820"
                20:   "7720"
                21:   "8720"
                22:   "9820"
                23:  "11020"
                24:  "12320"
                25:  "13720"
              level_for_daily_kudos:
                0:       "0"
                1:       "4"
                2:       "6"
                3:       "8"
                4:      "11"
                5:      "14"
                6:      "15"
                7:      "19"
                8:      "21"
                9:      "24"
                10:     "25"

      server_only:
        perm:
          201112:
            property:
              chat_config:
                reward_count_threshold: "5"
                reward_xp: "20"
              xp_config:
                daily_user_enter_xp: "30"
                initial_registration_xp: "10"
                first_time_xp: "10"
                first_time_story_room_xp: "30"
                receive_kudos_xp: "10"
                repeatable_multi_user_xp: "5"
                repeatable_story_room_xp: "10"
                repeatable_daily_cap: "100"
              session_config:
                reward_count_in_session_threshold: "5"
                reward_interactions_in_session_xp: "70"
            lookup:
              supported_single_user_props:
                drawing_board: "1"
                punching_bag: "1"
              supported_multi_user_props:
                pictionary: "1"
                trivia: "1"
                matchmaker: "1"
            rule:
              add_friend_first_time_xp:
                match_metric: "COUNT#withme_add_friend"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('first_time_xp')"
              chat_first_time_xp:
                match_metric: "COUNT#send_chat:*"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('first_time_xp')"
              initial_registration_xp:
                match_metric: "COUNT#user_registration"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('initial_registration_xp')"
              emote_first_time_xp:
                match_metric: "COUNT#send_emote"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('first_time_xp')"
              prop_in_room_count:
                match_metric: "COUNT#[prop:*:]*:[*]:*"
                condition: "lookup('supported_single_user_props', 'prop:[prop-name]:*') > 0 or
                            lookup('supported_multi_user_props', 'prop:[prop-name]:*') > 0"
                do_reward:
                  __captured_from_match__:
                    prefix: "withme_in_room_"
                    roll_ups: "COUNT"
                    value: "1"
              first_time_prop_xp:
                match_metric: "COUNT#withme_in_room_prop:*:*"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('first_time_xp')"
              first_time_avatar_to_avatar_interaction_xp:
                match_metric: "COUNT#avatar_to_avatar_interaction"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('first_time_xp')"
              prop_count_all_sessions:
                match_metric: "COUNT#[prop:]*:*:*:[*]"
                condition: "lookup('supported_single_user_props', 'prop:[prop-name]:*') > 0 or
                            lookup('supported_multi_user_props', 'prop:[prop-name]:*') > 0"
                do_reward:
                  __captured_from_match__:
                    prefix: "withme_session_"
                    roll_ups: "COUNT_PER_DAY"
                    value: "1"
              prop_count_session:
                match_metric: "COUNT_PER_DAY#withme_[session_prop]:*"
                with_config: "session_config"
                condition: "thisMetricOldValue() < configAsLong('reward_count_in_session_threshold') and
                            thisMetricNewValue() == configAsLong('reward_count_in_session_threshold')"
                do_reward:
                  __captured_from_match__:
                    prefix: "withme_daily_"
                    roll_ups: "COUNT_PER_DAY"
                    value: "1"
              prop_session_xp:
                match_metric: "COUNT_PER_DAY#withme_daily_session_prop"
                with_config: "session_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() == 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('reward_interactions_in_session_xp')"
              level_for_xp:
                match_metric: "SUM#withme_xp"
                condition: "thisMetricNewValue() > thisMetricOldValue()"
                do_reward:
                  withme_level:
                    roll_ups: "MAX"
                    value: "progression('xp_for_level','SUM#withme_xp')"
              story_room_first_complete_xp:
                match_metric: "COUNT#story_room:complete:*"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('first_time_story_room_xp')"
              story_room_complete_xp:
                match_metric: "COUNT#story_room:complete:*"
                with_config: "xp_config"
                condition: "metric('SUM_PER_DAY#withme_xp') < configAsLong('repeatable_daily_cap')"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM, SUM_PER_DAY"
                    value: "configAsLong('repeatable_story_room_xp')"
              receive_kudos_xp:
                match_metric: "COUNT#withme_kudo_type_*"
                with_config: "xp_config"
                condition: "thisMetricNewValue() > thisMetricOldValue()"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('receive_kudos_xp')"
              user_enter_app_daily_xp:
                match_metric: "COUNT_PER_DAY#withme_daily_user_enter_app"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() == 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('daily_user_enter_xp')"
              send_max_kudos_per_day:
                match_metric: "MAX#withme_level"
                condition: "thisMetricNewValue() > thisMetricOldValue()"
                do_reward:
                  withme_max_send_kudos_per_day:
                    roll_ups: "MAX"
                    value: "progression('level_for_daily_kudos','MAX#withme_level')"

      client_only:
        perm:
          201225:
            property:
              level_up_message:
                2:
                  en: "Two more levels to unlock Kudos"
                3:
                  en: "You reached level 3"
                4:
                  en: "One more level to unlock Destinations"
                5:
                  en: "Two more levels to unlock Daily Rewards"
                6:
                  en: "You reached level 6"
                7:
                  en: "Two more levels to unlock Destinations"
                8:
                  en: "You reached level 8"
                9:
                  en: "All Destinations are unlocked!"
                10:
                  en: "You reached level 10"
                11:
                  en: "You reached level 11"
                12:
                  en: "You reached level 12"
                13:
                  en: "You reached level 13"
                14:
                  en: "You reached level 14"
                15:
                  en: "You reached level 15"
                16:
                  en: "You reached level 16"
                17:
                  en: "You reached level 17"
                18:
                  en: "You reached level 18"
                19:
                  en: "You reached level 19"
                20:
                  en: "You reached level 20"
                21:
                  en: "You reached level 21"
                22:
                  en: "You reached level 22"
                23:
                  en: "You reached level 23"
                24:
                  en: "You reached level 24"
                25:
                  en: "You reached level 25"
