apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "etcd-cluster"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "3.3.12"
  repository: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/etcd
  pod:
    # annotation to avoid injecting evoy sidecar
    annotations:
      sidecar.istio.io/inject: "false"
    #
    # Deploying to mongodb tier
    #
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: int-2-tier
              operator: In
              values:
              - mongodb
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: etcd_cluster
                operator: In
                values:
                - etcd-cluster
            topologyKey: kubernetes.io/hostname
