#
# DON'T FORGET TO DEPLOY etcd-cluster-role before etcd-operator !!!!
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: etcd-operator
  template:
    metadata:
      labels:
        name: etcd-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: etcd-operator
        image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/etcd-operator:v0.9.4
        command:
        - etcd-operator
        # Uncomment to act for resources in all namespaces. More information in doc/user/clusterwide.md
        #- -cluster-wide
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      #
      # Deploying to mongodb tier
      # operator needs network access to cluster memebers
      #
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: int-2-tier
                operator: In
                values:
                - mongodb

