template_path: game-server-perf-tier.yaml
parameters:
  ClusterName: !resolver_yaml config/defaults.yml::EKS.ClusterName
  NodeGroupName: int-2-game-server-perf
  NodeInstanceType: 't3a.small'
  NodeImageId: !resolver_yaml config/defaults.yml::EKS.NodeImageId
  KeyName: kubernetes-int-2-key-pair
  NodeAutoScalingGroupMinSize: '1'
  NodeAutoScalingGroupMaxSize: '3'
  NodeAutoScalingGroupDesiredCapacity: '1'
  NodeVolumeSize: '80'
  NodeLabelARG: '--node-labels=int-2-tier=game-server-perf'
  KubeletReservedARG: '--kube-reserved cpu=250m,memory=0.5Gi,ephemeral-storage=1Gi'
  SystemReservedARG: '--system-reserved cpu=250m,memory=0.2Gi,ephemeral-storage=1Gi'
  EvictionHardARG: '--eviction-hard memory.available<500Mi,nodefs.available<10%'
  NodeSecurityGroup: sg-078e1578839437f3f
  VpcId: !stack_output_external int-2-eks-vpc::VpcId
  Subnets: !stack_output_external int-2-eks-vpc::SubnetIds
