apiVersion: v1
kind: ConfigMap
metadata:
  name: leaderboard-withme
  namespace: default
  labels:
    owned-by-microservice: configuration-manager
    repo: property
data:
  leaderboard_Withme.yaml: |
    leaderboard:
      client_and_server:
        perm:
          201112:
            property:
              chat_config:
                reward_rate_limit_sec: "60"
              xp_config:
                initial_registration_xp: "10"
            progression:
              xp_for_level:
                1:          "0"
                2:         "20"
                3:         "60"
                4:        "100"
                5:        "160"
                6:        "320"
                7:        "520"
                8:        "770"
                9:       "1070"
                10:      "1420"
                11:      "1820"
                12:      "2270"
                13:      "2770"
                14:      "3320"
                15:      "3920"
                16:      "4570"
                17:      "5270"
                18:      "6020"
                19:      "6820"
                20:      "7720"
                21:      "8720"
                22:      "9820"
                23:     "11020"
                24:     "12320"
                25:     "13720"
                26:     "15220"
                27:     "16820"
                28:     "18520"
                29:     "20320"
                30:     "22320"
                31:     "24520"
                32:     "26920"
                33:     "29520"
                34:     "32320"
                35:     "35320"
                36:     "38320"
                37:     "41320"
                38:     "44320"
                39:     "47320"
                40:     "50320"
              level_for_daily_kudos:
                0:          "0"
                1:          "4"
                2:          "6"
                3:          "8"
                4:         "11"
                5:         "14"
                6:         "15"
                7:         "19"
                8:         "21"
                9:         "24"
                10:        "25"
                11:        "27"
                12:        "29"
                13:        "31"
                14:        "32"
                15:        "35"
                16:        "38"
                17:        "39"
                18:        "40"

      server_only:
        perm:
          201112:
            property:
              chat_config:
                reward_count_threshold: "5"
                reward_xp: "20"
              xp_config:
                daily_user_enter_xp: "30"
                first_time_multi_user_xp: "5"
                first_time_xp: "10"
                first_time_story_room_xp: "40"
                receive_kudos_xp: "10"
                repeatable_multi_user_xp: "5"
                repeatable_story_room_xp: "10"
                repeatable_daily_cap: "100"
              session_config:
                reward_count_in_session_threshold: "5"
                reward_interactions_in_session_xp: "70"
              daily_config:
                min_level_for_daily_reward: "5"
            lookup:
              supported_single_user_props:
                drawingboard_tscn_a8c48ee188683965aad89dcfdbcb1471: "1"
                godog_tscn_e971d7a2d3d2e4cefc34e520d7289556: "1"
                mirror_tscn_c6a8ac4e2aa63e3f55d98b1f0e01715d: "1"
                o_drawingboard_01_tscn_b11bad4634665c7c95bd69e6eecf15ef: "1"
                o_kiosksigninteractive_subscene_01_tscn_c9e126fbd52197defdf86e58959853ee: "1"
                o_mirrorfloor_01_tscn_b714232d3aaa5cb5d12c7c84541b0919: "1"
                o_punchingbag_01_tscn_2655269b47f255ad06c9f840579b7490: "1"
                personalityquiz_root_tscn_d710335e76053df9a0a8609f0f043408: "1"
                personalitytest_tscn_6d07ed3ded9292da2c1c26b4de3fda55: "1"
                personalitytest_tscn_d6059a3a69a351ac1eb96c7ff8c9b763: "1"
                punchingbag_tscn_23fbdaf301cd37e4e540109d5573ecc6: "1"
                wandshootingrange_tscn_c5e85b72d8b45d73f89137ec4b38c3c6: "1"
                weather_scene_tscn_e0dda32aa75a0b3c8bb06fd8ccb179dd: "1"
                barista: "1"
                beachball: "1"
                bonfire: "1"
                coffee_maker: "1"
                dance_floor: "1"
                doggy: "1"
                drawing_game: "1"
                drawingboard: "1"
                fireworks: "1"
                hottub: "1"
                interactive_kiosk: "1"
                match_maker: "1"
                minidog: "1"
                mirror: "1"
                personality_test: "1"
                potion_machine: "1"
                punching_bag: "1"
                video_player: "1"
                wand_shooting_range: "1"
                weather: "1"
              supported_multi_user_props:
                dancefloor_danceposition_tscn_01b65090438d49891067a263c2f0f10a: "1"
                dancefloor_tscn_fe7461e5ff6c19dad4ed98b15510df18: "1"
                lobby_potion_machine_tscn_042cb4113b431d6ba267fa9fc2d9e94a: "1"
                matchmaker_tscn_0743712760220a59f8f5474207bff5b7: "1"
                potionmachine_tscn_4133667de5fa902ef5a43cd191c42aff: "1"
                triviagameentry_tscn_d44ef9fe56f431b9171330002bde9eb8: "1"
                videoplayer_tscn_3bc159b2385fbd1a31169e9a67a07d83: "1"
                trivia: "1"
            rule:
              add_friend_first_time_xp:
                match_metric: "COUNT#withme_add_friend"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('first_time_xp')"
              chat_first_time_xp:
                match_metric: "COUNT#send_chat:*"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('first_time_xp')"
              initial_registration_xp:
                match_metric: "COUNT#user_registration"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('initial_registration_xp')"
              emote_first_time_xp:
                match_metric: "COUNT#send_emote"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('first_time_xp')"
              prop_in_room_count:
                match_metric: "COUNT#[prop:*:]*:[*]:*"
                condition: "lookup('supported_single_user_props', 'prop:[prop-name]:*') > 0 or
                            lookup('supported_multi_user_props', 'prop:[prop-name]:*') > 0"
                do_reward:
                  __captured_from_match__:
                    prefix: "withme_in_room_"
                    roll_ups: "COUNT"
                    value: "1"
              first_time_prop_xp:
                match_metric: "COUNT#withme_in_room_prop:*:*"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "lookup('supported_multi_user_props', 'withme_in_room_prop:[prop-name]:*') > 0
                              ? configAsLong('first_time_multi_user_xp')
                              : configAsLong('first_time_xp')"
              first_time_avatar_to_avatar_interaction_xp:
                match_metric: "COUNT#avatar_to_avatar_interaction"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('first_time_xp')"
              prop_count_all_sessions:
                match_metric: "COUNT#[prop:]*:*:*:[*]"
                condition: "lookup('supported_single_user_props', 'prop:[prop-name]:*') > 0 or
                            lookup('supported_multi_user_props', 'prop:[prop-name]:*') > 0"
                do_reward:
                  __captured_from_match__:
                    prefix: "withme_session_"
                    roll_ups: "COUNT_PER_DAY"
                    value: "1"
              prop_count_session:
                match_metric: "COUNT_PER_DAY#withme_[session_prop]:*"
                with_config: "session_config"
                condition: "thisMetricOldValue() < configAsLong('reward_count_in_session_threshold') and
                            thisMetricNewValue() == configAsLong('reward_count_in_session_threshold')"
                do_reward:
                  __captured_from_match__:
                    prefix: "withme_daily_"
                    roll_ups: "COUNT_PER_DAY"
                    value: "1"
              prop_session_xp:
                match_metric: "COUNT_PER_DAY#withme_daily_session_prop"
                with_config: "session_config,daily_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() == 1 and
                            metric('MAX#withme_level') >= configAsLong('min_level_for_daily_reward')"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('reward_interactions_in_session_xp')"
              level_for_xp:
                match_metric: "SUM#withme_xp"
                condition: "thisMetricNewValue() > thisMetricOldValue()"
                do_reward:
                  withme_level:
                    roll_ups: "MAX"
                    value: "progression('xp_for_level','SUM#withme_xp')"
              story_room_first_complete_xp:
                match_metric: "COUNT#story_room:complete:*"
                with_config: "xp_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() >= 1"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('first_time_story_room_xp')"
              story_room_complete_xp:
                match_metric: "COUNT#story_room:complete:*"
                with_config: "xp_config"
                condition: "metric('SUM_PER_DAY#withme_xp') < configAsLong('repeatable_daily_cap')"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM, SUM_PER_DAY"
                    value: "configAsLong('repeatable_story_room_xp')"
              repeatable_multi_user_prop_xp:
                match_metric: "COUNT#withme_in_room_prop:*:*"
                with_config: "xp_config"
                condition: "lookup('supported_multi_user_props', 'withme_in_room_prop:[prop-name]:*') > 0 and
                            metric('SUM_PER_DAY#withme_xp') < configAsLong('repeatable_daily_cap')"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM, SUM_PER_DAY"
                    value: "configAsLong('repeatable_multi_user_xp')"
              receive_kudos_xp:
                match_metric: "COUNT#withme_kudo_type_*"
                with_config: "xp_config"
                condition: "thisMetricNewValue() > thisMetricOldValue()"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('receive_kudos_xp')"
              user_enter_app_daily_xp:
                match_metric: "COUNT_PER_DAY#withme_daily_user_enter_app"
                with_config: "xp_config,daily_config"
                condition: "thisMetricOldValue() < 1 and thisMetricNewValue() == 1 and
                            metric('MAX#withme_level') >= configAsLong('min_level_for_daily_reward')"
                do_reward:
                  withme_xp:
                    roll_ups: "SUM"
                    value: "configAsLong('daily_user_enter_xp')"
              level_up:
                match_metric: "MAX#withme_level"
                condition: "thisMetricNewValue() > thisMetricOldValue() and thisMetricNewValue() > 1"
                do_reward:
                  withme_max_send_kudos_per_day:
                    roll_ups: "MAX"
                    value: "progression('level_for_daily_kudos','MAX#withme_level')"
                do_send_message:
                  level_up:
                    data:
                      level:
                        type: "long"
                        expression: "thisMetricNewValue()"
                do_send_notification:
                  level_up:
                    data:
                      level:
                        type: "long"
                        expression: "thisMetricNewValue()"
                    title: "level_up.title"
                    body: "level_up.body"
                    arguments:
                      level:
                        type: "long"
                        expression: "thisMetricNewValue()"

      client_only:
        perm:
          201225:
            property:
              level_up_message:
                2:
                  en: "Great! Try more things to keep leveling up."
                3:
                  en: "Keep it up! 2 levels to unlock more rooms."
                4:
                  en: "Kudos! That’s what you’ve earned, well done."
                5:
                  en: "Nice! You’ve unlocked more rooms & rewards! 	"
                6:
                  en: "You did it! More kudos for you to share."
                7:
                  en: "Fantastic! More rooms to explore!"
                8:
                  en: "Yes! One more level to unlock ALL rooms!"
                9:
                  en: "Rockstar! Next level unlocks more clothing."
                10:
                  en: "Look at you - making it happen!"
                11:
                  en: "You reached level 11"
                12:
                  en: "You reached level 12"
                13:
                  en: "You reached level 13"
                14:
                  en: "You reached level 14"
                15:
                  en: "You reached level 15"
                16:
                  en: "You reached level 16"
                17:
                  en: "You reached level 17"
                18:
                  en: "You reached level 18"
                19:
                  en: "You reached level 19"
                20:
                  en: "You reached level 20"
                21:
                  en: "You reached level 21"
                22:
                  en: "You reached level 22"
                23:
                  en: "You reached level 23"
                24:
                  en: "You reached level 24"
                25:
                  en: "You reached level 25"
                26:
                  en: "You reached level 26"
                27:
                  en: "You reached level 27"
                28:
                  en: "You reached level 28"
                29:
                  en: "You reached level 29"
                30:
                  en: "You reached level 30"
                31:
                  en: "You reached level 31"
                32:
                  en: "You reached level 32"
                33:
                  en: "You reached level 33"
                34:
                  en: "You reached level 34"
                35:
                  en: "You reached level 35"
                36:
                  en: "You reached level 36"
                37:
                  en: "You reached level 37"
                38:
                  en: "You reached level 38"
                39:
                  en: "You reached level 39"
                40:
                  en: "You reached level 40"
