apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::417738154227:role/withme-services-int-us-west-2-aut-NodeInstanceRole-BDEV2R0KYW68
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::417738154227:role/xaccount-eks-ci
      username: hub-jenkins-infra0
      groups:
        - system:masters