{
 "title": "Game Server Managers",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Cloud-Hosted Game Servers by State (tier game_server)",
   "type": "graph",
   "description": "Displays the states for all the cloud-hosted game severs in the withme organization and game_server tier managed by the Game Server Manager",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cloud-Hosted Servers" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size{type=\"CLOUD_HOSTED_GAME_SERVER\", tier=\"game_server\", org=\"withme\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cloud-Hosted Game Servers by State (tier game_server2)",
   "type": "graph",
   "description": "Displays the states for all the cloud-hosted game severs in the withme organization and game_server tier managed by the Game Server Manager",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cloud-Hosted Servers" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size{type=\"CLOUD_HOSTED_GAME_SERVER\", tier=\"game_server2\", org=\"withme\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Game Server Node Count by Tier",
   "type": "graph",
   "description": "The number of Nodes hosting Game Server Pods in each tier.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_labels{label_prod_1_tier=~\"game-server.*\"}) by (label_prod_1_tier)",
     "legendFormat": "{{label_prod_1_tier}}"
    }
   ]
  },
  {
   "title": "Users In Game Sessions by Tier",
   "type": "graph",
   "description": "Plots the number of users in game sessions by tier",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_session_users_count) by (tier)",
     "legendFormat": "{{tier}}"
    }
   ]
  },
  {
   "title": "Game Server State Table Process Events Time",
   "type": "graph",
   "description": "The average and maximum duration for processing game server state table events.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(game_server_state_table_process_event_timer_seconds_sum[1m])/rate(game_server_state_table_process_event_timer_seconds_count[1m]))",
     "legendFormat": "MAX"
    },
    {
     "expr": "sum(rate(game_server_state_table_process_event_timer_seconds_sum[1m]))/sum(rate(game_server_state_table_process_event_timer_seconds_count[1m]))",
     "legendFormat": "AVE"
    }
   ]
  },
  {
   "title": "Game Server State Table Queue Size",
   "type": "graph",
   "description": "The size of the game server state table queue for each Pod.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_state_table_queue_size) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "State Table Request Count by Pod per Minute",
   "type": "graph",
   "description": "The number of state table requests processed per minute by each pod.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(game_server_state_table_process_event_timer_seconds_count[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Game Servers by Hosted Type",
   "type": "graph",
   "description": "The total number of game servers registered and grouped according to how they are hosted.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(game_server_proxy_cache_size) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}