AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create GameLift fleet'

Parameters:
  BuildId:
    Type: String
    Description: Build ID
  EC2InstanceType:
    Type: String
    Description: Instance Type
  InstanceCount:
    Type: Number
    Description: Number of EC2 Instances
  FleetType:
    Type: String
  NewGameSessionsPerCreator:
    Type: Number
    Description: A policy that limits the number of game sessions that an individual player can create on instances in this fleet within a specified span of time.
  PolicyPeriodInMinutes:
    Type: Number
  MaxSize:
    Type: Number
  MinSize:
    Type: Number
  Name:
    Type: String
  NewGameSessionProtectionPolicy:
    Type: String

Resources:
  GameLiftFleet:
    Type: AWS::GameLift::Fleet
    Properties:
      BuildId: !Ref BuildId
      Description: WithMe Game Server Fleet
      DesiredEC2Instances: !Ref InstanceCount
      EC2InboundPermissions:
        - FromPort: '7777'
          ToPort: '7778'
          IpRange: 0.0.0.0/0
          Protocol: TCP
      EC2InstanceType: !Ref EC2InstanceType
      FleetType: !Ref FleetType
      MaxSize: !Ref MaxSize
      MetricGroups: []
      MinSize: !Ref MinSize
      Name: !Ref Name
      NewGameSessionProtectionPolicy: !Ref NewGameSessionProtectionPolicy
      ResourceCreationLimitPolicy:
        NewGameSessionsPerCreator: !Ref NewGameSessionsPerCreator
        PolicyPeriodInMinutes: !Ref PolicyPeriodInMinutes
      RuntimeConfiguration:
        ServerProcesses:
          - LaunchPath: "/local/game/jre/bin/java"
            Parameters: -showversion -classpath "/local/game/classes:/local/game/config"               -Djava.ext.dirs=/local/game/libraries:/local/game/jre/lib/ext -DGAME_SERVER_PORT=7777                -Dspring.profiles.active=int-1 -DlogPath=/local/game com.withme.testgameserver.TestGameServer
            ConcurrentExecutions: 1


Outputs:
  FleetId:
    Description: The ID of the Gamelift Fleet
    Value: !Ref GameLiftFleet

