########## NOTE ##########
# UPR has dependencies on the "game-server-tier", "util-tier", "monitoring-tier" Sceptre stacks.
# So be aware if they are not updated to the latest state described in the Git repo they will be automatically updated with your updating "UPR" Sceptre Stack.
# controlVersion:1
template_path: upr-ecs-cluster.yaml

parameters:
  # The ECS Cluster Name
  ECSClusterName: prod-1-upr-cluster
  # Name of an existing EC2 KeyPair to enable SSH access to the ECS instances.
  KeyName: kubernetes-int-2-key-pair
  # VPC for UPR Security group.
  VpcId: !stack_output us-west-2/network/vpc.yaml::VpcId
  # Select at least two subnets in your selected VPC.
  SubnetId:
    - !stack_output us-west-2/network/vpc.yaml::PubSubnet01ID
    - !stack_output us-west-2/network/vpc.yaml::PubSubnet02ID
    - !stack_output us-west-2/network/vpc.yaml::PubSubnet03ID
  # ID of "game-server" tier SG 
  AGSsecurityGroupID: !stack_output us-west-2/game-server-tier/nodes.yaml::CustomSecurityGroup
  # ID of "game-server2" tier SG 
  AGS2securityGroupID: !stack_output us-west-2/game-server-tier/nodes2.yaml::CustomSecurityGroup
  # ID of "util" tier SG 
  UtilSecurityGroupID: !stack_output us-west-2/util-tier/nodes.yaml::CustomSecurityGroup
  # ID of "monitoring" tier SG 
  MonitoringSecurityGroupID: !stack_output us-west-2/monitoring-tier/nodes.yaml::CustomSecurityGroup
  # Number of instances to launch in your ECS cluster.
  DesiredCapacity: '3'
  # Maximum number of instances that can be launched in your ECS cluster.
  MaxSize: '12'
  # Minimum number of instances that can be launched in your ECS cluster.
  MinSize: '3'
  # Type of EC2 instance for ECS Cluster Node
  # When beta testing user base will grow (and routing requests to AGS will grow too)
  # we can migrate to'c5' instance type with bigger Network Performance.
  InstanceType: 't3.small'
  # EC2 Role name for attaching to "Instance Profile"
  EC2RoleName: !stack_output us-west-2/udp-routing/upr-iam.yaml::EC2roleNAME
  # AutoScaling Role ARN for attaching to "ApplicationAutoScaling"
  ASroleARN: !stack_output us-west-2/udp-routing/upr-iam.yaml::ASroleARN
  # UPR Docker image to run
  UPRImageName: '407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/upr:0.2.8'
  # NLB DNS to ETCD k8s Service Hostname and Properties
  ETCDHost: !stack_output us-west-2/udp-routing/upr-r53.yaml::HostedZoneDNSandPORT
