template_path: worker-nodes.yaml
dependencies:
  - us-west-2/microservice-tier/nodes.yaml

parameters:
  NodeSecurityGroup: !stack_output us-west-2/eks/cluster.yaml::NodeSecurityGroup
  ClusterName: !resolver_yaml config/defaults.yml::EKS.ClusterName
  NodeImageId: !resolver_yaml config/defaults.yml::EKS.NodeImageId
  VpcId: !stack_output us-west-2/network/vpc.yaml::VpcId
  Subnets:
    - !stack_output us-west-2/network/vpc.yaml::PrivSubnet01ID
    - !stack_output us-west-2/network/vpc.yaml::PrivSubnet02ID
    - !stack_output us-west-2/network/vpc.yaml::PrivSubnet03ID
  KeyName: kubernetes-int-2-key-pair
  CustomSecurityGroupName: gateway-tier
  NodeInstanceType: t3.medium
  NodeAutoScalingGroupMinSize: '3'
  NodeAutoScalingGroupMaxSize: '9'
  NodeAutoScalingGroupDesiredCapacity: '3'
  NodeVolumeSize: '64'
  NodeGroupName: perf-1-gateway-tier
  # Kubelet ARG'S
  NodeLabelARG: '--node-labels=perf-1-tier=gateway'
  KubeletReservedARG: '--kube-reserved cpu=250m,memory=0.5Gi,ephemeral-storage=1Gi'
  SystemReservedARG: '--system-reserved cpu=250m,memory=0.2Gi,ephemeral-storage=1Gi'
  EvictionHardARG: '--eviction-hard memory.available<500Mi,nodefs.available<10%'

sceptre_user_data:
  NodeRoleArn: "- rolearn: NodeRoleArn\n  username: system:node:{{ '{{EC2PrivateDNSName}}' }}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"
  NodeGroupName: "worker-nodes"
  FetchSavePath: !resolver_yaml config/defaults.yml::FetchSavePath

hooks:
  after_create:
    - !hook_eks ConfigMap::apply::aws-auth-append
    - !hook_eks ConfigMap::fetch::aws-auth@kube-system
  before_delete:
    - !hook_eks ConfigMap::delete::aws-auth@kube-system
