template_path: {{ var.deployment_target }}/gamelift-alias.yaml
dependencies:
  - {{ environment_variable.AWS_REGION }}/gamelift-create-fleet/fleet.yaml
stack_name: mmm-alias-{{ fleet_name_pattern }}


parameters:
  Name: mmm-alias-{{ fleet_name_pattern }}
  FleetId: !stack_output_external fleet-{{ fleet_name_pattern }}::FleetId
  Message: {{ var.message }}
  RoutingStrategyType: {{ var.routing_strategy_type }}
