template_path: gamelift-alias.yaml

parameters:
  AliasId: {{ var.alias_id }}
  Name: {{ var.name }}
  FleetId: !stack_output us-west-2/gamelift/fleet.yaml::FleetId
  Message: {{ var.message }}
  RoutingStrategyType: {{ var.routing_strategy_type }}
