template_path: gamelift-fleet.yaml
stack_name: {{ var.project_code }}-{{ var.environment }}-{{ environment_variable.AWS_REGION }}-{{ var.deployment_target }}-{{ var.game_server_name }}-{{ var.deployment_tag  | default("default")}}

parameters:
  BuildId: {{ environment_variable.GAMELIFT_BUILD_ID }}
  EC2InstanceType: {{ var.ec2_instance_type }}
  InstanceCount: "{{ var.instance_count  }}"
  FleetType: {{ var.fleet_type }}
  NewGameSessionsPerCreator: "{{ var.new_game_sessions_per_creator }}"
  PolicyPeriodInMinutes: "{{ var.policy_period_in_minutes }}"
  MaxSize: "{{ var.max_size }}"
  MinSize: "{{ var.min_size }}"
  Name: {{ var.environment }}-{{ environment_variable.AWS_REGION }}-{{ var.deployment_target }}-{{ var.game_server_name }}
  NewGameSessionProtectionPolicy: {{ var.new_game_session_protection_policy }}