template_path: gamelift-fleet.yaml
stack_name: fleet-{{ name_pattern }}

parameters:
  BuildId: {{ environment_variable.GAMELIFT_BUILD_ID }}
  EC2InstanceType: {{ var.ec2_instance_type }}
  InstanceCount: "{{ var.instance_count  }}"
  FleetType: {{ var.fleet_type }}
  NewGameSessionsPerCreator: "{{ var.new_game_sessions_per_creator }}"
  PolicyPeriodInMinutes: "{{ var.policy_period_in_minutes }}"
  MaxSize: "{{ var.max_size }}"
  MinSize: "{{ var.min_size }}"
  Name: {{ name_pattern }}
  NewGameSessionProtectionPolicy: {{ var.new_game_session_protection_policy }}
  InstanceRoleArn: {{ var.instance_role_arn}}