apiVersion: v1
kind: Service
metadata:
  name: mock-server
  labels:
    component: mock-server
    tier: mock-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: http-rest
  selector:
    component: mock-server
    tier: mock-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-server-deployment
  labels:
    component: mock-server
    tier: mock-server
spec:
  selector:
    matchLabels:
      component: mock-server
  replicas: 1
  template:
    metadata:
      labels:
        component: mock-server
        tier: mock-server
    spec:
      containers:
        - name: mock-server
          image: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-server/mock-server:5.5.1
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "DEBUG"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          ports:
            - name: serviceport
              containerPort: 8080
              protocol: TCP