project_code: {{ var.project_code }}
region: {{ environment_variable.AWS_REGION }}
name_prefix: {{ var.project_code }}-{{ var.environment }}-{{ environment_variable.AWS_REGION }}-{{ var.deployment_target }}-{{ var.game_server_name }}-{{ environment_variable.DEFAULT_TAG }}
