template_path: bastion.yaml
parameters:
  VPCID: !stack_output us-west-2/network/vpc.yaml::VpcId
  PublicSubnet1ID: !stack_output us-west-2/network/vpc.yaml::PubSubnet01ID
  PublicSubnet2ID: !stack_output us-west-2/network/vpc.yaml::PubSubnet02ID
  PublicSubnet3ID: !stack_output us-west-2/network/vpc.yaml::PubSubnet03ID
  ClusterName: !resolver_yaml config/defaults.yml::EKS.ClusterName
  ClusterArn: !stack_output us-west-2/eks/cluster.yaml::ClusterArn
  InstanceType: 't3.micro'
  BastionMinSize: '1'
  BastionMaxSize: '3'
  BastionDesiredCapacity: '2'
  RootVolumeSize: '120'
  LogsRetentionInDays: '30'
  HelmVersion: '3.2.3'
  VaultVersion: '1.4.3'
  GradleVersion: '5.4'
  SternVersion: '1.11.0'
  K9sVersion: '0.24.2'

sceptre_user_data:
  NodeRoleArn: "- rolearn: NodeRoleArn\n  username: bastion\n  groups:\n    - system:masters\n"
  NodeGroupName: "bastion-nodes"
  FetchSavePath: !resolver_yaml config/defaults.yml::FetchSavePath
  
hooks:
  after_create:
    - !hook_eks ConfigMap::apply::aws-auth-append
    - !hook_eks ConfigMap::fetch::aws-auth@kube-system
  before_delete:
    - !hook_eks ConfigMap::delete::aws-auth@kube-system