affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: perf-1-tier
          operator: In
          values:
          - mongodb

annotations: {}

extraArgs:
- --collect.collection
- --collect.database
- --collect.indexusage
- --collect.topmetrics
- --collect.connpoolstats

fullnameOverride: ""

image:
  pullPolicy: IfNotPresent
  repository: 407733091588.dkr.ecr.us-west-2.amazonaws.com/ego-cicd/kubedb-mongodb-exporter
  tag: v1.0.3

imagePullSecrets: []

livenessProbe:
  httpGet:
    path: /
    port: metrics
  initialDelaySeconds: 10

# [mongodb://][user:pass@]host1[:port1][,host2[:port2],...][/database][?options]
mongodb:
  uri: 

nameOverride: ""

nodeSelector: {}

podAnnotations: {}

port: "9216"

priorityClassName: ""

readinessProbe:
  httpGet:
    path: /
    port: metrics
  initialDelaySeconds: 10

replicas: 1

resources:
 limits:
   cpu: 300m
   memory: 256Mi
 requests:
   cpu: 100m
   memory: 128Mi

# Extra environment variables that will be passed into the exporter pod
env: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["all"]
  readOnlyRootFilesystem: true
  runAsGroup: 10000
  runAsNonRoot: true
  runAsUser: 10000

service:
  annotations: {}
  port: 9216
  type: ClusterIP

serviceAccount:
  create: true
  # If create is true and name is not set, then a name is generated using the
  # fullname template.
  name:

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring
  additionalLabels: 
    release: prom

tolerations: []