template_path: gamelift-alias-alone.yaml

parameters:
  AliasId: {{ var.alias_id }}
  Name: {{ var.name }}
  FleetId: !stack_output {{ environment_variable.AWS_REGION }}/gamelift-create-fleet/fleet.yaml::FleetId
  Message: {{ var.message }}
  RoutingStrategyType: {{ var.routing_strategy_type }}
