template_path: {{ var.deployment_target }}/gamelift-traffic-alias.yaml
stack_name: traffic-alias-{{ name_pattern }}


parameters:
  Name: {{ environment_variable.ORG_ID }}-{{ environment_variable.COMPAT_VERSION }}
  FleetId: !stack_output_external fleet-{{ name_pattern }}::FleetId
  Message: {{ var.message }}
  RoutingStrategyType: {{ var.routing_strategy_type }}
