template_path: gamelift-traffic-alias.yaml
stack_name: traffic-alias-{{ var.project_code }}-{{ var.environment }}-{{ environment_variable.AWS_REGION }}-{{ var.deployment_target }}-{{ var.game_server_name }}-{{ var.deployment_tag  | default("default")}}


parameters:
  Name: {{ var.org_id }}-{{ var.traffic_alias_suffix }}
  FleetId: {{ environment_variable.FLEET_ID | default("")}}
  Message: {{ var.message }}
  RoutingStrategyType: {{ var.routing_strategy_type }}
