template_path: gamelift-alias-alone.yaml
stack_name: {{ var.project_code }}-{{ var.environment }}-{{ environment_variable.AWS_REGION }}-{{ var.deployment_target }}-{{ var.game_server_name }}-{{ var.traffic_alias | default("") }}-{{ var.deployment_tag  | default("default")}}


parameters:
  Name: {{ "${var.org_id}-${var.traffic_alias}" | default("") }}
  FleetId: {{ environment_variable.FLEET_ID | default("")}}
  Message: {{ var.message }}
  RoutingStrategyType: {{ var.routing_strategy_type }}
