template_path: gamelift-traffic-alias.yaml
stack_name: traffic-alias-{{ var.project_code }}-{{ var.environment }}-{{ environment_variable.AWS_REGION }}-{{ var.deployment_target }}-{{ var.game_server_name }}-{{ environment_variable.DEPLOYMENT_TAG }}


parameters:
  Name: {{ environment_variable.ORG_ID }}-{{ environment_variable.COMPAT_VERSION }}
  FleetId: !stack_output_external fleet-{{ var.project_code }}-{{ var.environment }}-{{ environment_variable.AWS_REGION }}-{{ var.deployment_target }}-{{ var.game_server_name }}-{{ environment_variable.DEPLOYMENT_TAG }}::FleetId
  Message: {{ var.message }}
  RoutingStrategyType: {{ var.routing_strategy_type }}
