apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::132868707156:role/withme-services-perf-us-west-2-au-NodeInstanceRole-XB5PMI1QA30R
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::132868707156:role/xaccount-eks-ci
      username: hub-jenkins-infra0
      groups:
        - system:masters